/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mypipe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AquariusTransactionLogDelete extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 677945712918401221L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AquariusTransactionLogDelete\",\"namespace\":\"mypipe.avro\",\"fields\":[{\"name\":\"database\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"tableId\",\"type\":\"int\"},{\"name\":\"txid\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Guid\",\"size\":16}],\"default\":\"null\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"id\",\"type\":[\"long\",\"null\"]},{\"name\":\"transaction_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"open_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"amount\",\"type\":[\"double\",\"null\"]},{\"name\":\"create_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"type\",\"type\":[\"int\",\"null\"]},{\"name\":\"source_from_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"red_packet_id\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AquariusTransactionLogDelete> ENCODER =
      new BinaryMessageEncoder<AquariusTransactionLogDelete>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AquariusTransactionLogDelete> DECODER =
      new BinaryMessageDecoder<AquariusTransactionLogDelete>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AquariusTransactionLogDelete> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AquariusTransactionLogDelete> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AquariusTransactionLogDelete>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AquariusTransactionLogDelete to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AquariusTransactionLogDelete from a ByteBuffer. */
  public static AquariusTransactionLogDelete fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence database;
  @Deprecated public java.lang.CharSequence table;
  @Deprecated public int tableId;
  @Deprecated public mypipe.avro.Guid txid;
  @Deprecated public long timestamp;
  @Deprecated public java.lang.Long id;
  @Deprecated public java.lang.Long transaction_time;
  @Deprecated public java.lang.CharSequence open_id;
  @Deprecated public java.lang.Double amount;
  @Deprecated public java.lang.Long create_time;
  @Deprecated public java.lang.Integer type;
  @Deprecated public java.lang.Long source_from_id;
  @Deprecated public java.lang.Long red_packet_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AquariusTransactionLogDelete() {}

  /**
   * All-args constructor.
   * @param database The new value for database
   * @param table The new value for table
   * @param tableId The new value for tableId
   * @param txid The new value for txid
   * @param timestamp The new value for timestamp
   * @param id The new value for id
   * @param transaction_time The new value for transaction_time
   * @param open_id The new value for open_id
   * @param amount The new value for amount
   * @param create_time The new value for create_time
   * @param type The new value for type
   * @param source_from_id The new value for source_from_id
   * @param red_packet_id The new value for red_packet_id
   */
  public AquariusTransactionLogDelete(java.lang.CharSequence database, java.lang.CharSequence table, java.lang.Integer tableId, mypipe.avro.Guid txid, java.lang.Long timestamp, java.lang.Long id, java.lang.Long transaction_time, java.lang.CharSequence open_id, java.lang.Double amount, java.lang.Long create_time, java.lang.Integer type, java.lang.Long source_from_id, java.lang.Long red_packet_id) {
    this.database = database;
    this.table = table;
    this.tableId = tableId;
    this.txid = txid;
    this.timestamp = timestamp;
    this.id = id;
    this.transaction_time = transaction_time;
    this.open_id = open_id;
    this.amount = amount;
    this.create_time = create_time;
    this.type = type;
    this.source_from_id = source_from_id;
    this.red_packet_id = red_packet_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return database;
    case 1: return table;
    case 2: return tableId;
    case 3: return txid;
    case 4: return timestamp;
    case 5: return id;
    case 6: return transaction_time;
    case 7: return open_id;
    case 8: return amount;
    case 9: return create_time;
    case 10: return type;
    case 11: return source_from_id;
    case 12: return red_packet_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: database = (java.lang.CharSequence)value$; break;
    case 1: table = (java.lang.CharSequence)value$; break;
    case 2: tableId = (java.lang.Integer)value$; break;
    case 3: txid = (mypipe.avro.Guid)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: id = (java.lang.Long)value$; break;
    case 6: transaction_time = (java.lang.Long)value$; break;
    case 7: open_id = (java.lang.CharSequence)value$; break;
    case 8: amount = (java.lang.Double)value$; break;
    case 9: create_time = (java.lang.Long)value$; break;
    case 10: type = (java.lang.Integer)value$; break;
    case 11: source_from_id = (java.lang.Long)value$; break;
    case 12: red_packet_id = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'database' field.
   * @return The value of the 'database' field.
   */
  public java.lang.CharSequence getDatabase() {
    return database;
  }

  /**
   * Sets the value of the 'database' field.
   * @param value the value to set.
   */
  public void setDatabase(java.lang.CharSequence value) {
    this.database = value;
  }

  /**
   * Gets the value of the 'table' field.
   * @return The value of the 'table' field.
   */
  public java.lang.CharSequence getTable() {
    return table;
  }

  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(java.lang.CharSequence value) {
    this.table = value;
  }

  /**
   * Gets the value of the 'tableId' field.
   * @return The value of the 'tableId' field.
   */
  public java.lang.Integer getTableId() {
    return tableId;
  }

  /**
   * Sets the value of the 'tableId' field.
   * @param value the value to set.
   */
  public void setTableId(java.lang.Integer value) {
    this.tableId = value;
  }

  /**
   * Gets the value of the 'txid' field.
   * @return The value of the 'txid' field.
   */
  public mypipe.avro.Guid getTxid() {
    return txid;
  }

  /**
   * Sets the value of the 'txid' field.
   * @param value the value to set.
   */
  public void setTxid(mypipe.avro.Guid value) {
    this.txid = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'transaction_time' field.
   * @return The value of the 'transaction_time' field.
   */
  public java.lang.Long getTransactionTime() {
    return transaction_time;
  }

  /**
   * Sets the value of the 'transaction_time' field.
   * @param value the value to set.
   */
  public void setTransactionTime(java.lang.Long value) {
    this.transaction_time = value;
  }

  /**
   * Gets the value of the 'open_id' field.
   * @return The value of the 'open_id' field.
   */
  public java.lang.CharSequence getOpenId() {
    return open_id;
  }

  /**
   * Sets the value of the 'open_id' field.
   * @param value the value to set.
   */
  public void setOpenId(java.lang.CharSequence value) {
    this.open_id = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.lang.Double getAmount() {
    return amount;
  }

  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.Double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'create_time' field.
   * @return The value of the 'create_time' field.
   */
  public java.lang.Long getCreateTime() {
    return create_time;
  }

  /**
   * Sets the value of the 'create_time' field.
   * @param value the value to set.
   */
  public void setCreateTime(java.lang.Long value) {
    this.create_time = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.Integer getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.Integer value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'source_from_id' field.
   * @return The value of the 'source_from_id' field.
   */
  public java.lang.Long getSourceFromId() {
    return source_from_id;
  }

  /**
   * Sets the value of the 'source_from_id' field.
   * @param value the value to set.
   */
  public void setSourceFromId(java.lang.Long value) {
    this.source_from_id = value;
  }

  /**
   * Gets the value of the 'red_packet_id' field.
   * @return The value of the 'red_packet_id' field.
   */
  public java.lang.Long getRedPacketId() {
    return red_packet_id;
  }

  /**
   * Sets the value of the 'red_packet_id' field.
   * @param value the value to set.
   */
  public void setRedPacketId(java.lang.Long value) {
    this.red_packet_id = value;
  }

  /**
   * Creates a new AquariusTransactionLogDelete RecordBuilder.
   * @return A new AquariusTransactionLogDelete RecordBuilder
   */
  public static mypipe.avro.AquariusTransactionLogDelete.Builder newBuilder() {
    return new mypipe.avro.AquariusTransactionLogDelete.Builder();
  }

  /**
   * Creates a new AquariusTransactionLogDelete RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AquariusTransactionLogDelete RecordBuilder
   */
  public static mypipe.avro.AquariusTransactionLogDelete.Builder newBuilder(mypipe.avro.AquariusTransactionLogDelete.Builder other) {
    return new mypipe.avro.AquariusTransactionLogDelete.Builder(other);
  }

  /**
   * Creates a new AquariusTransactionLogDelete RecordBuilder by copying an existing AquariusTransactionLogDelete instance.
   * @param other The existing instance to copy.
   * @return A new AquariusTransactionLogDelete RecordBuilder
   */
  public static mypipe.avro.AquariusTransactionLogDelete.Builder newBuilder(mypipe.avro.AquariusTransactionLogDelete other) {
    return new mypipe.avro.AquariusTransactionLogDelete.Builder(other);
  }

  /**
   * RecordBuilder for AquariusTransactionLogDelete instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AquariusTransactionLogDelete>
    implements org.apache.avro.data.RecordBuilder<AquariusTransactionLogDelete> {

    private java.lang.CharSequence database;
    private java.lang.CharSequence table;
    private int tableId;
    private mypipe.avro.Guid txid;
    private long timestamp;
    private java.lang.Long id;
    private java.lang.Long transaction_time;
    private java.lang.CharSequence open_id;
    private java.lang.Double amount;
    private java.lang.Long create_time;
    private java.lang.Integer type;
    private java.lang.Long source_from_id;
    private java.lang.Long red_packet_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mypipe.avro.AquariusTransactionLogDelete.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.transaction_time)) {
        this.transaction_time = data().deepCopy(fields()[6].schema(), other.transaction_time);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.open_id)) {
        this.open_id = data().deepCopy(fields()[7].schema(), other.open_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.amount)) {
        this.amount = data().deepCopy(fields()[8].schema(), other.amount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.create_time)) {
        this.create_time = data().deepCopy(fields()[9].schema(), other.create_time);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.type)) {
        this.type = data().deepCopy(fields()[10].schema(), other.type);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.source_from_id)) {
        this.source_from_id = data().deepCopy(fields()[11].schema(), other.source_from_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.red_packet_id)) {
        this.red_packet_id = data().deepCopy(fields()[12].schema(), other.red_packet_id);
        fieldSetFlags()[12] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AquariusTransactionLogDelete instance
     * @param other The existing instance to copy.
     */
    private Builder(mypipe.avro.AquariusTransactionLogDelete other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.transaction_time)) {
        this.transaction_time = data().deepCopy(fields()[6].schema(), other.transaction_time);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.open_id)) {
        this.open_id = data().deepCopy(fields()[7].schema(), other.open_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.amount)) {
        this.amount = data().deepCopy(fields()[8].schema(), other.amount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.create_time)) {
        this.create_time = data().deepCopy(fields()[9].schema(), other.create_time);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.type)) {
        this.type = data().deepCopy(fields()[10].schema(), other.type);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.source_from_id)) {
        this.source_from_id = data().deepCopy(fields()[11].schema(), other.source_from_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.red_packet_id)) {
        this.red_packet_id = data().deepCopy(fields()[12].schema(), other.red_packet_id);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'database' field.
      * @return The value.
      */
    public java.lang.CharSequence getDatabase() {
      return database;
    }

    /**
      * Sets the value of the 'database' field.
      * @param value The value of 'database'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setDatabase(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.database = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'database' field has been set.
      * @return True if the 'database' field has been set, false otherwise.
      */
    public boolean hasDatabase() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'database' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearDatabase() {
      database = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'table' field.
      * @return The value.
      */
    public java.lang.CharSequence getTable() {
      return table;
    }

    /**
      * Sets the value of the 'table' field.
      * @param value The value of 'table'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setTable(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.table = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'table' field has been set.
      * @return True if the 'table' field has been set, false otherwise.
      */
    public boolean hasTable() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'table' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearTable() {
      table = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tableId' field.
      * @return The value.
      */
    public java.lang.Integer getTableId() {
      return tableId;
    }

    /**
      * Sets the value of the 'tableId' field.
      * @param value The value of 'tableId'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setTableId(int value) {
      validate(fields()[2], value);
      this.tableId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tableId' field has been set.
      * @return True if the 'tableId' field has been set, false otherwise.
      */
    public boolean hasTableId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tableId' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearTableId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'txid' field.
      * @return The value.
      */
    public mypipe.avro.Guid getTxid() {
      return txid;
    }

    /**
      * Sets the value of the 'txid' field.
      * @param value The value of 'txid'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setTxid(mypipe.avro.Guid value) {
      validate(fields()[3], value);
      this.txid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'txid' field has been set.
      * @return True if the 'txid' field has been set, false otherwise.
      */
    public boolean hasTxid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'txid' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearTxid() {
      txid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setId(java.lang.Long value) {
      validate(fields()[5], value);
      this.id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearId() {
      id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'transaction_time' field.
      * @return The value.
      */
    public java.lang.Long getTransactionTime() {
      return transaction_time;
    }

    /**
      * Sets the value of the 'transaction_time' field.
      * @param value The value of 'transaction_time'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setTransactionTime(java.lang.Long value) {
      validate(fields()[6], value);
      this.transaction_time = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_time' field has been set.
      * @return True if the 'transaction_time' field has been set, false otherwise.
      */
    public boolean hasTransactionTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'transaction_time' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearTransactionTime() {
      transaction_time = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'open_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpenId() {
      return open_id;
    }

    /**
      * Sets the value of the 'open_id' field.
      * @param value The value of 'open_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setOpenId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.open_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'open_id' field has been set.
      * @return True if the 'open_id' field has been set, false otherwise.
      */
    public boolean hasOpenId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'open_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearOpenId() {
      open_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.lang.Double getAmount() {
      return amount;
    }

    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setAmount(java.lang.Double value) {
      validate(fields()[8], value);
      this.amount = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'create_time' field.
      * @return The value.
      */
    public java.lang.Long getCreateTime() {
      return create_time;
    }

    /**
      * Sets the value of the 'create_time' field.
      * @param value The value of 'create_time'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setCreateTime(java.lang.Long value) {
      validate(fields()[9], value);
      this.create_time = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'create_time' field has been set.
      * @return True if the 'create_time' field has been set, false otherwise.
      */
    public boolean hasCreateTime() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'create_time' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearCreateTime() {
      create_time = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.Integer getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setType(java.lang.Integer value) {
      validate(fields()[10], value);
      this.type = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearType() {
      type = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_from_id' field.
      * @return The value.
      */
    public java.lang.Long getSourceFromId() {
      return source_from_id;
    }

    /**
      * Sets the value of the 'source_from_id' field.
      * @param value The value of 'source_from_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setSourceFromId(java.lang.Long value) {
      validate(fields()[11], value);
      this.source_from_id = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'source_from_id' field has been set.
      * @return True if the 'source_from_id' field has been set, false otherwise.
      */
    public boolean hasSourceFromId() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'source_from_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearSourceFromId() {
      source_from_id = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'red_packet_id' field.
      * @return The value.
      */
    public java.lang.Long getRedPacketId() {
      return red_packet_id;
    }

    /**
      * Sets the value of the 'red_packet_id' field.
      * @param value The value of 'red_packet_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder setRedPacketId(java.lang.Long value) {
      validate(fields()[12], value);
      this.red_packet_id = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'red_packet_id' field has been set.
      * @return True if the 'red_packet_id' field has been set, false otherwise.
      */
    public boolean hasRedPacketId() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'red_packet_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusTransactionLogDelete.Builder clearRedPacketId() {
      red_packet_id = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AquariusTransactionLogDelete build() {
      try {
        AquariusTransactionLogDelete record = new AquariusTransactionLogDelete();
        record.database = fieldSetFlags()[0] ? this.database : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.table = fieldSetFlags()[1] ? this.table : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tableId = fieldSetFlags()[2] ? this.tableId : (java.lang.Integer) defaultValue(fields()[2]);
        record.txid = fieldSetFlags()[3] ? this.txid : (mypipe.avro.Guid) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.id = fieldSetFlags()[5] ? this.id : (java.lang.Long) defaultValue(fields()[5]);
        record.transaction_time = fieldSetFlags()[6] ? this.transaction_time : (java.lang.Long) defaultValue(fields()[6]);
        record.open_id = fieldSetFlags()[7] ? this.open_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.amount = fieldSetFlags()[8] ? this.amount : (java.lang.Double) defaultValue(fields()[8]);
        record.create_time = fieldSetFlags()[9] ? this.create_time : (java.lang.Long) defaultValue(fields()[9]);
        record.type = fieldSetFlags()[10] ? this.type : (java.lang.Integer) defaultValue(fields()[10]);
        record.source_from_id = fieldSetFlags()[11] ? this.source_from_id : (java.lang.Long) defaultValue(fields()[11]);
        record.red_packet_id = fieldSetFlags()[12] ? this.red_packet_id : (java.lang.Long) defaultValue(fields()[12]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AquariusTransactionLogDelete>
    WRITER$ = (org.apache.avro.io.DatumWriter<AquariusTransactionLogDelete>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AquariusTransactionLogDelete>
    READER$ = (org.apache.avro.io.DatumReader<AquariusTransactionLogDelete>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
