/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mypipe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AquariusRedPacketReceiveRecordUpdate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4362738328203259678L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AquariusRedPacketReceiveRecordUpdate\",\"namespace\":\"mypipe.avro\",\"fields\":[{\"name\":\"database\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"tableId\",\"type\":\"int\"},{\"name\":\"txid\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Guid\",\"size\":16}],\"default\":\"null\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"old_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"new_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"old_open_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"new_open_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"old_red_packet_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"new_red_packet_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"old_amount\",\"type\":[\"double\",\"null\"]},{\"name\":\"new_amount\",\"type\":[\"double\",\"null\"]},{\"name\":\"old_create_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"new_create_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"old_is_transaction_record\",\"type\":[\"int\",\"null\"]},{\"name\":\"new_is_transaction_record\",\"type\":[\"int\",\"null\"]},{\"name\":\"old_media_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"new_media_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"old_media_length\",\"type\":[\"int\",\"null\"]},{\"name\":\"new_media_length\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AquariusRedPacketReceiveRecordUpdate> ENCODER =
      new BinaryMessageEncoder<AquariusRedPacketReceiveRecordUpdate>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AquariusRedPacketReceiveRecordUpdate> DECODER =
      new BinaryMessageDecoder<AquariusRedPacketReceiveRecordUpdate>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AquariusRedPacketReceiveRecordUpdate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AquariusRedPacketReceiveRecordUpdate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AquariusRedPacketReceiveRecordUpdate>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AquariusRedPacketReceiveRecordUpdate to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AquariusRedPacketReceiveRecordUpdate from a ByteBuffer. */
  public static AquariusRedPacketReceiveRecordUpdate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence database;
  @Deprecated public java.lang.CharSequence table;
  @Deprecated public int tableId;
  @Deprecated public mypipe.avro.Guid txid;
  @Deprecated public long timestamp;
  @Deprecated public java.lang.Long old_id;
  @Deprecated public java.lang.Long new_id;
  @Deprecated public java.lang.CharSequence old_open_id;
  @Deprecated public java.lang.CharSequence new_open_id;
  @Deprecated public java.lang.Long old_red_packet_id;
  @Deprecated public java.lang.Long new_red_packet_id;
  @Deprecated public java.lang.Double old_amount;
  @Deprecated public java.lang.Double new_amount;
  @Deprecated public java.lang.Long old_create_time;
  @Deprecated public java.lang.Long new_create_time;
  @Deprecated public java.lang.Integer old_is_transaction_record;
  @Deprecated public java.lang.Integer new_is_transaction_record;
  @Deprecated public java.lang.CharSequence old_media_url;
  @Deprecated public java.lang.CharSequence new_media_url;
  @Deprecated public java.lang.Integer old_media_length;
  @Deprecated public java.lang.Integer new_media_length;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AquariusRedPacketReceiveRecordUpdate() {}

  /**
   * All-args constructor.
   * @param database The new value for database
   * @param table The new value for table
   * @param tableId The new value for tableId
   * @param txid The new value for txid
   * @param timestamp The new value for timestamp
   * @param old_id The new value for old_id
   * @param new_id The new value for new_id
   * @param old_open_id The new value for old_open_id
   * @param new_open_id The new value for new_open_id
   * @param old_red_packet_id The new value for old_red_packet_id
   * @param new_red_packet_id The new value for new_red_packet_id
   * @param old_amount The new value for old_amount
   * @param new_amount The new value for new_amount
   * @param old_create_time The new value for old_create_time
   * @param new_create_time The new value for new_create_time
   * @param old_is_transaction_record The new value for old_is_transaction_record
   * @param new_is_transaction_record The new value for new_is_transaction_record
   * @param old_media_url The new value for old_media_url
   * @param new_media_url The new value for new_media_url
   * @param old_media_length The new value for old_media_length
   * @param new_media_length The new value for new_media_length
   */
  public AquariusRedPacketReceiveRecordUpdate(java.lang.CharSequence database, java.lang.CharSequence table, java.lang.Integer tableId, mypipe.avro.Guid txid, java.lang.Long timestamp, java.lang.Long old_id, java.lang.Long new_id, java.lang.CharSequence old_open_id, java.lang.CharSequence new_open_id, java.lang.Long old_red_packet_id, java.lang.Long new_red_packet_id, java.lang.Double old_amount, java.lang.Double new_amount, java.lang.Long old_create_time, java.lang.Long new_create_time, java.lang.Integer old_is_transaction_record, java.lang.Integer new_is_transaction_record, java.lang.CharSequence old_media_url, java.lang.CharSequence new_media_url, java.lang.Integer old_media_length, java.lang.Integer new_media_length) {
    this.database = database;
    this.table = table;
    this.tableId = tableId;
    this.txid = txid;
    this.timestamp = timestamp;
    this.old_id = old_id;
    this.new_id = new_id;
    this.old_open_id = old_open_id;
    this.new_open_id = new_open_id;
    this.old_red_packet_id = old_red_packet_id;
    this.new_red_packet_id = new_red_packet_id;
    this.old_amount = old_amount;
    this.new_amount = new_amount;
    this.old_create_time = old_create_time;
    this.new_create_time = new_create_time;
    this.old_is_transaction_record = old_is_transaction_record;
    this.new_is_transaction_record = new_is_transaction_record;
    this.old_media_url = old_media_url;
    this.new_media_url = new_media_url;
    this.old_media_length = old_media_length;
    this.new_media_length = new_media_length;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return database;
    case 1: return table;
    case 2: return tableId;
    case 3: return txid;
    case 4: return timestamp;
    case 5: return old_id;
    case 6: return new_id;
    case 7: return old_open_id;
    case 8: return new_open_id;
    case 9: return old_red_packet_id;
    case 10: return new_red_packet_id;
    case 11: return old_amount;
    case 12: return new_amount;
    case 13: return old_create_time;
    case 14: return new_create_time;
    case 15: return old_is_transaction_record;
    case 16: return new_is_transaction_record;
    case 17: return old_media_url;
    case 18: return new_media_url;
    case 19: return old_media_length;
    case 20: return new_media_length;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: database = (java.lang.CharSequence)value$; break;
    case 1: table = (java.lang.CharSequence)value$; break;
    case 2: tableId = (java.lang.Integer)value$; break;
    case 3: txid = (mypipe.avro.Guid)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: old_id = (java.lang.Long)value$; break;
    case 6: new_id = (java.lang.Long)value$; break;
    case 7: old_open_id = (java.lang.CharSequence)value$; break;
    case 8: new_open_id = (java.lang.CharSequence)value$; break;
    case 9: old_red_packet_id = (java.lang.Long)value$; break;
    case 10: new_red_packet_id = (java.lang.Long)value$; break;
    case 11: old_amount = (java.lang.Double)value$; break;
    case 12: new_amount = (java.lang.Double)value$; break;
    case 13: old_create_time = (java.lang.Long)value$; break;
    case 14: new_create_time = (java.lang.Long)value$; break;
    case 15: old_is_transaction_record = (java.lang.Integer)value$; break;
    case 16: new_is_transaction_record = (java.lang.Integer)value$; break;
    case 17: old_media_url = (java.lang.CharSequence)value$; break;
    case 18: new_media_url = (java.lang.CharSequence)value$; break;
    case 19: old_media_length = (java.lang.Integer)value$; break;
    case 20: new_media_length = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'database' field.
   * @return The value of the 'database' field.
   */
  public java.lang.CharSequence getDatabase() {
    return database;
  }

  /**
   * Sets the value of the 'database' field.
   * @param value the value to set.
   */
  public void setDatabase(java.lang.CharSequence value) {
    this.database = value;
  }

  /**
   * Gets the value of the 'table' field.
   * @return The value of the 'table' field.
   */
  public java.lang.CharSequence getTable() {
    return table;
  }

  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(java.lang.CharSequence value) {
    this.table = value;
  }

  /**
   * Gets the value of the 'tableId' field.
   * @return The value of the 'tableId' field.
   */
  public java.lang.Integer getTableId() {
    return tableId;
  }

  /**
   * Sets the value of the 'tableId' field.
   * @param value the value to set.
   */
  public void setTableId(java.lang.Integer value) {
    this.tableId = value;
  }

  /**
   * Gets the value of the 'txid' field.
   * @return The value of the 'txid' field.
   */
  public mypipe.avro.Guid getTxid() {
    return txid;
  }

  /**
   * Sets the value of the 'txid' field.
   * @param value the value to set.
   */
  public void setTxid(mypipe.avro.Guid value) {
    this.txid = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'old_id' field.
   * @return The value of the 'old_id' field.
   */
  public java.lang.Long getOldId() {
    return old_id;
  }

  /**
   * Sets the value of the 'old_id' field.
   * @param value the value to set.
   */
  public void setOldId(java.lang.Long value) {
    this.old_id = value;
  }

  /**
   * Gets the value of the 'new_id' field.
   * @return The value of the 'new_id' field.
   */
  public java.lang.Long getNewId() {
    return new_id;
  }

  /**
   * Sets the value of the 'new_id' field.
   * @param value the value to set.
   */
  public void setNewId(java.lang.Long value) {
    this.new_id = value;
  }

  /**
   * Gets the value of the 'old_open_id' field.
   * @return The value of the 'old_open_id' field.
   */
  public java.lang.CharSequence getOldOpenId() {
    return old_open_id;
  }

  /**
   * Sets the value of the 'old_open_id' field.
   * @param value the value to set.
   */
  public void setOldOpenId(java.lang.CharSequence value) {
    this.old_open_id = value;
  }

  /**
   * Gets the value of the 'new_open_id' field.
   * @return The value of the 'new_open_id' field.
   */
  public java.lang.CharSequence getNewOpenId() {
    return new_open_id;
  }

  /**
   * Sets the value of the 'new_open_id' field.
   * @param value the value to set.
   */
  public void setNewOpenId(java.lang.CharSequence value) {
    this.new_open_id = value;
  }

  /**
   * Gets the value of the 'old_red_packet_id' field.
   * @return The value of the 'old_red_packet_id' field.
   */
  public java.lang.Long getOldRedPacketId() {
    return old_red_packet_id;
  }

  /**
   * Sets the value of the 'old_red_packet_id' field.
   * @param value the value to set.
   */
  public void setOldRedPacketId(java.lang.Long value) {
    this.old_red_packet_id = value;
  }

  /**
   * Gets the value of the 'new_red_packet_id' field.
   * @return The value of the 'new_red_packet_id' field.
   */
  public java.lang.Long getNewRedPacketId() {
    return new_red_packet_id;
  }

  /**
   * Sets the value of the 'new_red_packet_id' field.
   * @param value the value to set.
   */
  public void setNewRedPacketId(java.lang.Long value) {
    this.new_red_packet_id = value;
  }

  /**
   * Gets the value of the 'old_amount' field.
   * @return The value of the 'old_amount' field.
   */
  public java.lang.Double getOldAmount() {
    return old_amount;
  }

  /**
   * Sets the value of the 'old_amount' field.
   * @param value the value to set.
   */
  public void setOldAmount(java.lang.Double value) {
    this.old_amount = value;
  }

  /**
   * Gets the value of the 'new_amount' field.
   * @return The value of the 'new_amount' field.
   */
  public java.lang.Double getNewAmount() {
    return new_amount;
  }

  /**
   * Sets the value of the 'new_amount' field.
   * @param value the value to set.
   */
  public void setNewAmount(java.lang.Double value) {
    this.new_amount = value;
  }

  /**
   * Gets the value of the 'old_create_time' field.
   * @return The value of the 'old_create_time' field.
   */
  public java.lang.Long getOldCreateTime() {
    return old_create_time;
  }

  /**
   * Sets the value of the 'old_create_time' field.
   * @param value the value to set.
   */
  public void setOldCreateTime(java.lang.Long value) {
    this.old_create_time = value;
  }

  /**
   * Gets the value of the 'new_create_time' field.
   * @return The value of the 'new_create_time' field.
   */
  public java.lang.Long getNewCreateTime() {
    return new_create_time;
  }

  /**
   * Sets the value of the 'new_create_time' field.
   * @param value the value to set.
   */
  public void setNewCreateTime(java.lang.Long value) {
    this.new_create_time = value;
  }

  /**
   * Gets the value of the 'old_is_transaction_record' field.
   * @return The value of the 'old_is_transaction_record' field.
   */
  public java.lang.Integer getOldIsTransactionRecord() {
    return old_is_transaction_record;
  }

  /**
   * Sets the value of the 'old_is_transaction_record' field.
   * @param value the value to set.
   */
  public void setOldIsTransactionRecord(java.lang.Integer value) {
    this.old_is_transaction_record = value;
  }

  /**
   * Gets the value of the 'new_is_transaction_record' field.
   * @return The value of the 'new_is_transaction_record' field.
   */
  public java.lang.Integer getNewIsTransactionRecord() {
    return new_is_transaction_record;
  }

  /**
   * Sets the value of the 'new_is_transaction_record' field.
   * @param value the value to set.
   */
  public void setNewIsTransactionRecord(java.lang.Integer value) {
    this.new_is_transaction_record = value;
  }

  /**
   * Gets the value of the 'old_media_url' field.
   * @return The value of the 'old_media_url' field.
   */
  public java.lang.CharSequence getOldMediaUrl() {
    return old_media_url;
  }

  /**
   * Sets the value of the 'old_media_url' field.
   * @param value the value to set.
   */
  public void setOldMediaUrl(java.lang.CharSequence value) {
    this.old_media_url = value;
  }

  /**
   * Gets the value of the 'new_media_url' field.
   * @return The value of the 'new_media_url' field.
   */
  public java.lang.CharSequence getNewMediaUrl() {
    return new_media_url;
  }

  /**
   * Sets the value of the 'new_media_url' field.
   * @param value the value to set.
   */
  public void setNewMediaUrl(java.lang.CharSequence value) {
    this.new_media_url = value;
  }

  /**
   * Gets the value of the 'old_media_length' field.
   * @return The value of the 'old_media_length' field.
   */
  public java.lang.Integer getOldMediaLength() {
    return old_media_length;
  }

  /**
   * Sets the value of the 'old_media_length' field.
   * @param value the value to set.
   */
  public void setOldMediaLength(java.lang.Integer value) {
    this.old_media_length = value;
  }

  /**
   * Gets the value of the 'new_media_length' field.
   * @return The value of the 'new_media_length' field.
   */
  public java.lang.Integer getNewMediaLength() {
    return new_media_length;
  }

  /**
   * Sets the value of the 'new_media_length' field.
   * @param value the value to set.
   */
  public void setNewMediaLength(java.lang.Integer value) {
    this.new_media_length = value;
  }

  /**
   * Creates a new AquariusRedPacketReceiveRecordUpdate RecordBuilder.
   * @return A new AquariusRedPacketReceiveRecordUpdate RecordBuilder
   */
  public static mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder newBuilder() {
    return new mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder();
  }

  /**
   * Creates a new AquariusRedPacketReceiveRecordUpdate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AquariusRedPacketReceiveRecordUpdate RecordBuilder
   */
  public static mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder newBuilder(mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder other) {
    return new mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder(other);
  }

  /**
   * Creates a new AquariusRedPacketReceiveRecordUpdate RecordBuilder by copying an existing AquariusRedPacketReceiveRecordUpdate instance.
   * @param other The existing instance to copy.
   * @return A new AquariusRedPacketReceiveRecordUpdate RecordBuilder
   */
  public static mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder newBuilder(mypipe.avro.AquariusRedPacketReceiveRecordUpdate other) {
    return new mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder(other);
  }

  /**
   * RecordBuilder for AquariusRedPacketReceiveRecordUpdate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AquariusRedPacketReceiveRecordUpdate>
    implements org.apache.avro.data.RecordBuilder<AquariusRedPacketReceiveRecordUpdate> {

    private java.lang.CharSequence database;
    private java.lang.CharSequence table;
    private int tableId;
    private mypipe.avro.Guid txid;
    private long timestamp;
    private java.lang.Long old_id;
    private java.lang.Long new_id;
    private java.lang.CharSequence old_open_id;
    private java.lang.CharSequence new_open_id;
    private java.lang.Long old_red_packet_id;
    private java.lang.Long new_red_packet_id;
    private java.lang.Double old_amount;
    private java.lang.Double new_amount;
    private java.lang.Long old_create_time;
    private java.lang.Long new_create_time;
    private java.lang.Integer old_is_transaction_record;
    private java.lang.Integer new_is_transaction_record;
    private java.lang.CharSequence old_media_url;
    private java.lang.CharSequence new_media_url;
    private java.lang.Integer old_media_length;
    private java.lang.Integer new_media_length;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.old_id)) {
        this.old_id = data().deepCopy(fields()[5].schema(), other.old_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.new_id)) {
        this.new_id = data().deepCopy(fields()[6].schema(), other.new_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.old_open_id)) {
        this.old_open_id = data().deepCopy(fields()[7].schema(), other.old_open_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.new_open_id)) {
        this.new_open_id = data().deepCopy(fields()[8].schema(), other.new_open_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.old_red_packet_id)) {
        this.old_red_packet_id = data().deepCopy(fields()[9].schema(), other.old_red_packet_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.new_red_packet_id)) {
        this.new_red_packet_id = data().deepCopy(fields()[10].schema(), other.new_red_packet_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.old_amount)) {
        this.old_amount = data().deepCopy(fields()[11].schema(), other.old_amount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.new_amount)) {
        this.new_amount = data().deepCopy(fields()[12].schema(), other.new_amount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.old_create_time)) {
        this.old_create_time = data().deepCopy(fields()[13].schema(), other.old_create_time);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.new_create_time)) {
        this.new_create_time = data().deepCopy(fields()[14].schema(), other.new_create_time);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.old_is_transaction_record)) {
        this.old_is_transaction_record = data().deepCopy(fields()[15].schema(), other.old_is_transaction_record);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.new_is_transaction_record)) {
        this.new_is_transaction_record = data().deepCopy(fields()[16].schema(), other.new_is_transaction_record);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.old_media_url)) {
        this.old_media_url = data().deepCopy(fields()[17].schema(), other.old_media_url);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.new_media_url)) {
        this.new_media_url = data().deepCopy(fields()[18].schema(), other.new_media_url);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.old_media_length)) {
        this.old_media_length = data().deepCopy(fields()[19].schema(), other.old_media_length);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.new_media_length)) {
        this.new_media_length = data().deepCopy(fields()[20].schema(), other.new_media_length);
        fieldSetFlags()[20] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AquariusRedPacketReceiveRecordUpdate instance
     * @param other The existing instance to copy.
     */
    private Builder(mypipe.avro.AquariusRedPacketReceiveRecordUpdate other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.old_id)) {
        this.old_id = data().deepCopy(fields()[5].schema(), other.old_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.new_id)) {
        this.new_id = data().deepCopy(fields()[6].schema(), other.new_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.old_open_id)) {
        this.old_open_id = data().deepCopy(fields()[7].schema(), other.old_open_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.new_open_id)) {
        this.new_open_id = data().deepCopy(fields()[8].schema(), other.new_open_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.old_red_packet_id)) {
        this.old_red_packet_id = data().deepCopy(fields()[9].schema(), other.old_red_packet_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.new_red_packet_id)) {
        this.new_red_packet_id = data().deepCopy(fields()[10].schema(), other.new_red_packet_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.old_amount)) {
        this.old_amount = data().deepCopy(fields()[11].schema(), other.old_amount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.new_amount)) {
        this.new_amount = data().deepCopy(fields()[12].schema(), other.new_amount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.old_create_time)) {
        this.old_create_time = data().deepCopy(fields()[13].schema(), other.old_create_time);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.new_create_time)) {
        this.new_create_time = data().deepCopy(fields()[14].schema(), other.new_create_time);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.old_is_transaction_record)) {
        this.old_is_transaction_record = data().deepCopy(fields()[15].schema(), other.old_is_transaction_record);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.new_is_transaction_record)) {
        this.new_is_transaction_record = data().deepCopy(fields()[16].schema(), other.new_is_transaction_record);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.old_media_url)) {
        this.old_media_url = data().deepCopy(fields()[17].schema(), other.old_media_url);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.new_media_url)) {
        this.new_media_url = data().deepCopy(fields()[18].schema(), other.new_media_url);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.old_media_length)) {
        this.old_media_length = data().deepCopy(fields()[19].schema(), other.old_media_length);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.new_media_length)) {
        this.new_media_length = data().deepCopy(fields()[20].schema(), other.new_media_length);
        fieldSetFlags()[20] = true;
      }
    }

    /**
      * Gets the value of the 'database' field.
      * @return The value.
      */
    public java.lang.CharSequence getDatabase() {
      return database;
    }

    /**
      * Sets the value of the 'database' field.
      * @param value The value of 'database'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setDatabase(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.database = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'database' field has been set.
      * @return True if the 'database' field has been set, false otherwise.
      */
    public boolean hasDatabase() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'database' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearDatabase() {
      database = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'table' field.
      * @return The value.
      */
    public java.lang.CharSequence getTable() {
      return table;
    }

    /**
      * Sets the value of the 'table' field.
      * @param value The value of 'table'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setTable(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.table = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'table' field has been set.
      * @return True if the 'table' field has been set, false otherwise.
      */
    public boolean hasTable() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'table' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearTable() {
      table = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tableId' field.
      * @return The value.
      */
    public java.lang.Integer getTableId() {
      return tableId;
    }

    /**
      * Sets the value of the 'tableId' field.
      * @param value The value of 'tableId'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setTableId(int value) {
      validate(fields()[2], value);
      this.tableId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tableId' field has been set.
      * @return True if the 'tableId' field has been set, false otherwise.
      */
    public boolean hasTableId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tableId' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearTableId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'txid' field.
      * @return The value.
      */
    public mypipe.avro.Guid getTxid() {
      return txid;
    }

    /**
      * Sets the value of the 'txid' field.
      * @param value The value of 'txid'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setTxid(mypipe.avro.Guid value) {
      validate(fields()[3], value);
      this.txid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'txid' field has been set.
      * @return True if the 'txid' field has been set, false otherwise.
      */
    public boolean hasTxid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'txid' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearTxid() {
      txid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_id' field.
      * @return The value.
      */
    public java.lang.Long getOldId() {
      return old_id;
    }

    /**
      * Sets the value of the 'old_id' field.
      * @param value The value of 'old_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldId(java.lang.Long value) {
      validate(fields()[5], value);
      this.old_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'old_id' field has been set.
      * @return True if the 'old_id' field has been set, false otherwise.
      */
    public boolean hasOldId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'old_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldId() {
      old_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_id' field.
      * @return The value.
      */
    public java.lang.Long getNewId() {
      return new_id;
    }

    /**
      * Sets the value of the 'new_id' field.
      * @param value The value of 'new_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewId(java.lang.Long value) {
      validate(fields()[6], value);
      this.new_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'new_id' field has been set.
      * @return True if the 'new_id' field has been set, false otherwise.
      */
    public boolean hasNewId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'new_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewId() {
      new_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_open_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getOldOpenId() {
      return old_open_id;
    }

    /**
      * Sets the value of the 'old_open_id' field.
      * @param value The value of 'old_open_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldOpenId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.old_open_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'old_open_id' field has been set.
      * @return True if the 'old_open_id' field has been set, false otherwise.
      */
    public boolean hasOldOpenId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'old_open_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldOpenId() {
      old_open_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_open_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewOpenId() {
      return new_open_id;
    }

    /**
      * Sets the value of the 'new_open_id' field.
      * @param value The value of 'new_open_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewOpenId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.new_open_id = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'new_open_id' field has been set.
      * @return True if the 'new_open_id' field has been set, false otherwise.
      */
    public boolean hasNewOpenId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'new_open_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewOpenId() {
      new_open_id = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_red_packet_id' field.
      * @return The value.
      */
    public java.lang.Long getOldRedPacketId() {
      return old_red_packet_id;
    }

    /**
      * Sets the value of the 'old_red_packet_id' field.
      * @param value The value of 'old_red_packet_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldRedPacketId(java.lang.Long value) {
      validate(fields()[9], value);
      this.old_red_packet_id = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'old_red_packet_id' field has been set.
      * @return True if the 'old_red_packet_id' field has been set, false otherwise.
      */
    public boolean hasOldRedPacketId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'old_red_packet_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldRedPacketId() {
      old_red_packet_id = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_red_packet_id' field.
      * @return The value.
      */
    public java.lang.Long getNewRedPacketId() {
      return new_red_packet_id;
    }

    /**
      * Sets the value of the 'new_red_packet_id' field.
      * @param value The value of 'new_red_packet_id'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewRedPacketId(java.lang.Long value) {
      validate(fields()[10], value);
      this.new_red_packet_id = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'new_red_packet_id' field has been set.
      * @return True if the 'new_red_packet_id' field has been set, false otherwise.
      */
    public boolean hasNewRedPacketId() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'new_red_packet_id' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewRedPacketId() {
      new_red_packet_id = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_amount' field.
      * @return The value.
      */
    public java.lang.Double getOldAmount() {
      return old_amount;
    }

    /**
      * Sets the value of the 'old_amount' field.
      * @param value The value of 'old_amount'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldAmount(java.lang.Double value) {
      validate(fields()[11], value);
      this.old_amount = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'old_amount' field has been set.
      * @return True if the 'old_amount' field has been set, false otherwise.
      */
    public boolean hasOldAmount() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'old_amount' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldAmount() {
      old_amount = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_amount' field.
      * @return The value.
      */
    public java.lang.Double getNewAmount() {
      return new_amount;
    }

    /**
      * Sets the value of the 'new_amount' field.
      * @param value The value of 'new_amount'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewAmount(java.lang.Double value) {
      validate(fields()[12], value);
      this.new_amount = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'new_amount' field has been set.
      * @return True if the 'new_amount' field has been set, false otherwise.
      */
    public boolean hasNewAmount() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'new_amount' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewAmount() {
      new_amount = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_create_time' field.
      * @return The value.
      */
    public java.lang.Long getOldCreateTime() {
      return old_create_time;
    }

    /**
      * Sets the value of the 'old_create_time' field.
      * @param value The value of 'old_create_time'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldCreateTime(java.lang.Long value) {
      validate(fields()[13], value);
      this.old_create_time = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'old_create_time' field has been set.
      * @return True if the 'old_create_time' field has been set, false otherwise.
      */
    public boolean hasOldCreateTime() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'old_create_time' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldCreateTime() {
      old_create_time = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_create_time' field.
      * @return The value.
      */
    public java.lang.Long getNewCreateTime() {
      return new_create_time;
    }

    /**
      * Sets the value of the 'new_create_time' field.
      * @param value The value of 'new_create_time'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewCreateTime(java.lang.Long value) {
      validate(fields()[14], value);
      this.new_create_time = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'new_create_time' field has been set.
      * @return True if the 'new_create_time' field has been set, false otherwise.
      */
    public boolean hasNewCreateTime() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'new_create_time' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewCreateTime() {
      new_create_time = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_is_transaction_record' field.
      * @return The value.
      */
    public java.lang.Integer getOldIsTransactionRecord() {
      return old_is_transaction_record;
    }

    /**
      * Sets the value of the 'old_is_transaction_record' field.
      * @param value The value of 'old_is_transaction_record'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldIsTransactionRecord(java.lang.Integer value) {
      validate(fields()[15], value);
      this.old_is_transaction_record = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'old_is_transaction_record' field has been set.
      * @return True if the 'old_is_transaction_record' field has been set, false otherwise.
      */
    public boolean hasOldIsTransactionRecord() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'old_is_transaction_record' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldIsTransactionRecord() {
      old_is_transaction_record = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_is_transaction_record' field.
      * @return The value.
      */
    public java.lang.Integer getNewIsTransactionRecord() {
      return new_is_transaction_record;
    }

    /**
      * Sets the value of the 'new_is_transaction_record' field.
      * @param value The value of 'new_is_transaction_record'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewIsTransactionRecord(java.lang.Integer value) {
      validate(fields()[16], value);
      this.new_is_transaction_record = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'new_is_transaction_record' field has been set.
      * @return True if the 'new_is_transaction_record' field has been set, false otherwise.
      */
    public boolean hasNewIsTransactionRecord() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'new_is_transaction_record' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewIsTransactionRecord() {
      new_is_transaction_record = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_media_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getOldMediaUrl() {
      return old_media_url;
    }

    /**
      * Sets the value of the 'old_media_url' field.
      * @param value The value of 'old_media_url'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldMediaUrl(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.old_media_url = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'old_media_url' field has been set.
      * @return True if the 'old_media_url' field has been set, false otherwise.
      */
    public boolean hasOldMediaUrl() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'old_media_url' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldMediaUrl() {
      old_media_url = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_media_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewMediaUrl() {
      return new_media_url;
    }

    /**
      * Sets the value of the 'new_media_url' field.
      * @param value The value of 'new_media_url'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewMediaUrl(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.new_media_url = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'new_media_url' field has been set.
      * @return True if the 'new_media_url' field has been set, false otherwise.
      */
    public boolean hasNewMediaUrl() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'new_media_url' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewMediaUrl() {
      new_media_url = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'old_media_length' field.
      * @return The value.
      */
    public java.lang.Integer getOldMediaLength() {
      return old_media_length;
    }

    /**
      * Sets the value of the 'old_media_length' field.
      * @param value The value of 'old_media_length'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setOldMediaLength(java.lang.Integer value) {
      validate(fields()[19], value);
      this.old_media_length = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'old_media_length' field has been set.
      * @return True if the 'old_media_length' field has been set, false otherwise.
      */
    public boolean hasOldMediaLength() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'old_media_length' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearOldMediaLength() {
      old_media_length = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'new_media_length' field.
      * @return The value.
      */
    public java.lang.Integer getNewMediaLength() {
      return new_media_length;
    }

    /**
      * Sets the value of the 'new_media_length' field.
      * @param value The value of 'new_media_length'.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder setNewMediaLength(java.lang.Integer value) {
      validate(fields()[20], value);
      this.new_media_length = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'new_media_length' field has been set.
      * @return True if the 'new_media_length' field has been set, false otherwise.
      */
    public boolean hasNewMediaLength() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'new_media_length' field.
      * @return This builder.
      */
    public mypipe.avro.AquariusRedPacketReceiveRecordUpdate.Builder clearNewMediaLength() {
      new_media_length = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AquariusRedPacketReceiveRecordUpdate build() {
      try {
        AquariusRedPacketReceiveRecordUpdate record = new AquariusRedPacketReceiveRecordUpdate();
        record.database = fieldSetFlags()[0] ? this.database : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.table = fieldSetFlags()[1] ? this.table : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tableId = fieldSetFlags()[2] ? this.tableId : (java.lang.Integer) defaultValue(fields()[2]);
        record.txid = fieldSetFlags()[3] ? this.txid : (mypipe.avro.Guid) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.old_id = fieldSetFlags()[5] ? this.old_id : (java.lang.Long) defaultValue(fields()[5]);
        record.new_id = fieldSetFlags()[6] ? this.new_id : (java.lang.Long) defaultValue(fields()[6]);
        record.old_open_id = fieldSetFlags()[7] ? this.old_open_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.new_open_id = fieldSetFlags()[8] ? this.new_open_id : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.old_red_packet_id = fieldSetFlags()[9] ? this.old_red_packet_id : (java.lang.Long) defaultValue(fields()[9]);
        record.new_red_packet_id = fieldSetFlags()[10] ? this.new_red_packet_id : (java.lang.Long) defaultValue(fields()[10]);
        record.old_amount = fieldSetFlags()[11] ? this.old_amount : (java.lang.Double) defaultValue(fields()[11]);
        record.new_amount = fieldSetFlags()[12] ? this.new_amount : (java.lang.Double) defaultValue(fields()[12]);
        record.old_create_time = fieldSetFlags()[13] ? this.old_create_time : (java.lang.Long) defaultValue(fields()[13]);
        record.new_create_time = fieldSetFlags()[14] ? this.new_create_time : (java.lang.Long) defaultValue(fields()[14]);
        record.old_is_transaction_record = fieldSetFlags()[15] ? this.old_is_transaction_record : (java.lang.Integer) defaultValue(fields()[15]);
        record.new_is_transaction_record = fieldSetFlags()[16] ? this.new_is_transaction_record : (java.lang.Integer) defaultValue(fields()[16]);
        record.old_media_url = fieldSetFlags()[17] ? this.old_media_url : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.new_media_url = fieldSetFlags()[18] ? this.new_media_url : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.old_media_length = fieldSetFlags()[19] ? this.old_media_length : (java.lang.Integer) defaultValue(fields()[19]);
        record.new_media_length = fieldSetFlags()[20] ? this.new_media_length : (java.lang.Integer) defaultValue(fields()[20]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AquariusRedPacketReceiveRecordUpdate>
    WRITER$ = (org.apache.avro.io.DatumWriter<AquariusRedPacketReceiveRecordUpdate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AquariusRedPacketReceiveRecordUpdate>
    READER$ = (org.apache.avro.io.DatumReader<AquariusRedPacketReceiveRecordUpdate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
