/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mypipe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ForumUserDelete extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5969670367950317138L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ForumUserDelete\",\"namespace\":\"mypipe.avro\",\"fields\":[{\"name\":\"database\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"tableId\",\"type\":\"int\"},{\"name\":\"txid\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Guid\",\"size\":16}],\"default\":\"null\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"id\",\"type\":[\"long\",\"null\"]},{\"name\":\"nick_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"user_sign\",\"type\":[\"string\",\"null\"]},{\"name\":\"platform\",\"type\":[\"int\",\"null\"]},{\"name\":\"passwd\",\"type\":[\"string\",\"null\"]},{\"name\":\"head_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"salt\",\"type\":[\"string\",\"null\"]},{\"name\":\"create_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"last_update_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"status\",\"type\":[\"int\",\"null\"]},{\"name\":\"score\",\"type\":[\"float\",\"null\"]},{\"name\":\"app\",\"type\":[\"int\",\"null\"]},{\"name\":\"level\",\"type\":[\"int\",\"null\"]},{\"name\":\"level_upd_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"reward_flower_count\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ForumUserDelete> ENCODER =
      new BinaryMessageEncoder<ForumUserDelete>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ForumUserDelete> DECODER =
      new BinaryMessageDecoder<ForumUserDelete>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ForumUserDelete> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ForumUserDelete> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ForumUserDelete>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ForumUserDelete to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ForumUserDelete from a ByteBuffer. */
  public static ForumUserDelete fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence database;
  @Deprecated public java.lang.CharSequence table;
  @Deprecated public int tableId;
  @Deprecated public mypipe.avro.Guid txid;
  @Deprecated public long timestamp;
  @Deprecated public java.lang.Long id;
  @Deprecated public java.lang.CharSequence nick_name;
  @Deprecated public java.lang.CharSequence user_sign;
  @Deprecated public java.lang.Integer platform;
  @Deprecated public java.lang.CharSequence passwd;
  @Deprecated public java.lang.CharSequence head_url;
  @Deprecated public java.lang.CharSequence salt;
  @Deprecated public java.lang.Long create_time;
  @Deprecated public java.lang.Long last_update_time;
  @Deprecated public java.lang.Integer status;
  @Deprecated public java.lang.Float score;
  @Deprecated public java.lang.Integer app;
  @Deprecated public java.lang.Integer level;
  @Deprecated public java.lang.Long level_upd_time;
  @Deprecated public java.lang.Integer reward_flower_count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ForumUserDelete() {}

  /**
   * All-args constructor.
   * @param database The new value for database
   * @param table The new value for table
   * @param tableId The new value for tableId
   * @param txid The new value for txid
   * @param timestamp The new value for timestamp
   * @param id The new value for id
   * @param nick_name The new value for nick_name
   * @param user_sign The new value for user_sign
   * @param platform The new value for platform
   * @param passwd The new value for passwd
   * @param head_url The new value for head_url
   * @param salt The new value for salt
   * @param create_time The new value for create_time
   * @param last_update_time The new value for last_update_time
   * @param status The new value for status
   * @param score The new value for score
   * @param app The new value for app
   * @param level The new value for level
   * @param level_upd_time The new value for level_upd_time
   * @param reward_flower_count The new value for reward_flower_count
   */
  public ForumUserDelete(java.lang.CharSequence database, java.lang.CharSequence table, java.lang.Integer tableId, mypipe.avro.Guid txid, java.lang.Long timestamp, java.lang.Long id, java.lang.CharSequence nick_name, java.lang.CharSequence user_sign, java.lang.Integer platform, java.lang.CharSequence passwd, java.lang.CharSequence head_url, java.lang.CharSequence salt, java.lang.Long create_time, java.lang.Long last_update_time, java.lang.Integer status, java.lang.Float score, java.lang.Integer app, java.lang.Integer level, java.lang.Long level_upd_time, java.lang.Integer reward_flower_count) {
    this.database = database;
    this.table = table;
    this.tableId = tableId;
    this.txid = txid;
    this.timestamp = timestamp;
    this.id = id;
    this.nick_name = nick_name;
    this.user_sign = user_sign;
    this.platform = platform;
    this.passwd = passwd;
    this.head_url = head_url;
    this.salt = salt;
    this.create_time = create_time;
    this.last_update_time = last_update_time;
    this.status = status;
    this.score = score;
    this.app = app;
    this.level = level;
    this.level_upd_time = level_upd_time;
    this.reward_flower_count = reward_flower_count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return database;
    case 1: return table;
    case 2: return tableId;
    case 3: return txid;
    case 4: return timestamp;
    case 5: return id;
    case 6: return nick_name;
    case 7: return user_sign;
    case 8: return platform;
    case 9: return passwd;
    case 10: return head_url;
    case 11: return salt;
    case 12: return create_time;
    case 13: return last_update_time;
    case 14: return status;
    case 15: return score;
    case 16: return app;
    case 17: return level;
    case 18: return level_upd_time;
    case 19: return reward_flower_count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: database = (java.lang.CharSequence)value$; break;
    case 1: table = (java.lang.CharSequence)value$; break;
    case 2: tableId = (java.lang.Integer)value$; break;
    case 3: txid = (mypipe.avro.Guid)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: id = (java.lang.Long)value$; break;
    case 6: nick_name = (java.lang.CharSequence)value$; break;
    case 7: user_sign = (java.lang.CharSequence)value$; break;
    case 8: platform = (java.lang.Integer)value$; break;
    case 9: passwd = (java.lang.CharSequence)value$; break;
    case 10: head_url = (java.lang.CharSequence)value$; break;
    case 11: salt = (java.lang.CharSequence)value$; break;
    case 12: create_time = (java.lang.Long)value$; break;
    case 13: last_update_time = (java.lang.Long)value$; break;
    case 14: status = (java.lang.Integer)value$; break;
    case 15: score = (java.lang.Float)value$; break;
    case 16: app = (java.lang.Integer)value$; break;
    case 17: level = (java.lang.Integer)value$; break;
    case 18: level_upd_time = (java.lang.Long)value$; break;
    case 19: reward_flower_count = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'database' field.
   * @return The value of the 'database' field.
   */
  public java.lang.CharSequence getDatabase() {
    return database;
  }

  /**
   * Sets the value of the 'database' field.
   * @param value the value to set.
   */
  public void setDatabase(java.lang.CharSequence value) {
    this.database = value;
  }

  /**
   * Gets the value of the 'table' field.
   * @return The value of the 'table' field.
   */
  public java.lang.CharSequence getTable() {
    return table;
  }

  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(java.lang.CharSequence value) {
    this.table = value;
  }

  /**
   * Gets the value of the 'tableId' field.
   * @return The value of the 'tableId' field.
   */
  public java.lang.Integer getTableId() {
    return tableId;
  }

  /**
   * Sets the value of the 'tableId' field.
   * @param value the value to set.
   */
  public void setTableId(java.lang.Integer value) {
    this.tableId = value;
  }

  /**
   * Gets the value of the 'txid' field.
   * @return The value of the 'txid' field.
   */
  public mypipe.avro.Guid getTxid() {
    return txid;
  }

  /**
   * Sets the value of the 'txid' field.
   * @param value the value to set.
   */
  public void setTxid(mypipe.avro.Guid value) {
    this.txid = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'nick_name' field.
   * @return The value of the 'nick_name' field.
   */
  public java.lang.CharSequence getNickName() {
    return nick_name;
  }

  /**
   * Sets the value of the 'nick_name' field.
   * @param value the value to set.
   */
  public void setNickName(java.lang.CharSequence value) {
    this.nick_name = value;
  }

  /**
   * Gets the value of the 'user_sign' field.
   * @return The value of the 'user_sign' field.
   */
  public java.lang.CharSequence getUserSign() {
    return user_sign;
  }

  /**
   * Sets the value of the 'user_sign' field.
   * @param value the value to set.
   */
  public void setUserSign(java.lang.CharSequence value) {
    this.user_sign = value;
  }

  /**
   * Gets the value of the 'platform' field.
   * @return The value of the 'platform' field.
   */
  public java.lang.Integer getPlatform() {
    return platform;
  }

  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.Integer value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'passwd' field.
   * @return The value of the 'passwd' field.
   */
  public java.lang.CharSequence getPasswd() {
    return passwd;
  }

  /**
   * Sets the value of the 'passwd' field.
   * @param value the value to set.
   */
  public void setPasswd(java.lang.CharSequence value) {
    this.passwd = value;
  }

  /**
   * Gets the value of the 'head_url' field.
   * @return The value of the 'head_url' field.
   */
  public java.lang.CharSequence getHeadUrl() {
    return head_url;
  }

  /**
   * Sets the value of the 'head_url' field.
   * @param value the value to set.
   */
  public void setHeadUrl(java.lang.CharSequence value) {
    this.head_url = value;
  }

  /**
   * Gets the value of the 'salt' field.
   * @return The value of the 'salt' field.
   */
  public java.lang.CharSequence getSalt() {
    return salt;
  }

  /**
   * Sets the value of the 'salt' field.
   * @param value the value to set.
   */
  public void setSalt(java.lang.CharSequence value) {
    this.salt = value;
  }

  /**
   * Gets the value of the 'create_time' field.
   * @return The value of the 'create_time' field.
   */
  public java.lang.Long getCreateTime() {
    return create_time;
  }

  /**
   * Sets the value of the 'create_time' field.
   * @param value the value to set.
   */
  public void setCreateTime(java.lang.Long value) {
    this.create_time = value;
  }

  /**
   * Gets the value of the 'last_update_time' field.
   * @return The value of the 'last_update_time' field.
   */
  public java.lang.Long getLastUpdateTime() {
    return last_update_time;
  }

  /**
   * Sets the value of the 'last_update_time' field.
   * @param value the value to set.
   */
  public void setLastUpdateTime(java.lang.Long value) {
    this.last_update_time = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Integer value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'score' field.
   * @return The value of the 'score' field.
   */
  public java.lang.Float getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Float value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'app' field.
   * @return The value of the 'app' field.
   */
  public java.lang.Integer getApp() {
    return app;
  }

  /**
   * Sets the value of the 'app' field.
   * @param value the value to set.
   */
  public void setApp(java.lang.Integer value) {
    this.app = value;
  }

  /**
   * Gets the value of the 'level' field.
   * @return The value of the 'level' field.
   */
  public java.lang.Integer getLevel() {
    return level;
  }

  /**
   * Sets the value of the 'level' field.
   * @param value the value to set.
   */
  public void setLevel(java.lang.Integer value) {
    this.level = value;
  }

  /**
   * Gets the value of the 'level_upd_time' field.
   * @return The value of the 'level_upd_time' field.
   */
  public java.lang.Long getLevelUpdTime() {
    return level_upd_time;
  }

  /**
   * Sets the value of the 'level_upd_time' field.
   * @param value the value to set.
   */
  public void setLevelUpdTime(java.lang.Long value) {
    this.level_upd_time = value;
  }

  /**
   * Gets the value of the 'reward_flower_count' field.
   * @return The value of the 'reward_flower_count' field.
   */
  public java.lang.Integer getRewardFlowerCount() {
    return reward_flower_count;
  }

  /**
   * Sets the value of the 'reward_flower_count' field.
   * @param value the value to set.
   */
  public void setRewardFlowerCount(java.lang.Integer value) {
    this.reward_flower_count = value;
  }

  /**
   * Creates a new ForumUserDelete RecordBuilder.
   * @return A new ForumUserDelete RecordBuilder
   */
  public static mypipe.avro.ForumUserDelete.Builder newBuilder() {
    return new mypipe.avro.ForumUserDelete.Builder();
  }

  /**
   * Creates a new ForumUserDelete RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ForumUserDelete RecordBuilder
   */
  public static mypipe.avro.ForumUserDelete.Builder newBuilder(mypipe.avro.ForumUserDelete.Builder other) {
    return new mypipe.avro.ForumUserDelete.Builder(other);
  }

  /**
   * Creates a new ForumUserDelete RecordBuilder by copying an existing ForumUserDelete instance.
   * @param other The existing instance to copy.
   * @return A new ForumUserDelete RecordBuilder
   */
  public static mypipe.avro.ForumUserDelete.Builder newBuilder(mypipe.avro.ForumUserDelete other) {
    return new mypipe.avro.ForumUserDelete.Builder(other);
  }

  /**
   * RecordBuilder for ForumUserDelete instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ForumUserDelete>
    implements org.apache.avro.data.RecordBuilder<ForumUserDelete> {

    private java.lang.CharSequence database;
    private java.lang.CharSequence table;
    private int tableId;
    private mypipe.avro.Guid txid;
    private long timestamp;
    private java.lang.Long id;
    private java.lang.CharSequence nick_name;
    private java.lang.CharSequence user_sign;
    private java.lang.Integer platform;
    private java.lang.CharSequence passwd;
    private java.lang.CharSequence head_url;
    private java.lang.CharSequence salt;
    private java.lang.Long create_time;
    private java.lang.Long last_update_time;
    private java.lang.Integer status;
    private java.lang.Float score;
    private java.lang.Integer app;
    private java.lang.Integer level;
    private java.lang.Long level_upd_time;
    private java.lang.Integer reward_flower_count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mypipe.avro.ForumUserDelete.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.nick_name)) {
        this.nick_name = data().deepCopy(fields()[6].schema(), other.nick_name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.user_sign)) {
        this.user_sign = data().deepCopy(fields()[7].schema(), other.user_sign);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.platform)) {
        this.platform = data().deepCopy(fields()[8].schema(), other.platform);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.passwd)) {
        this.passwd = data().deepCopy(fields()[9].schema(), other.passwd);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.head_url)) {
        this.head_url = data().deepCopy(fields()[10].schema(), other.head_url);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.salt)) {
        this.salt = data().deepCopy(fields()[11].schema(), other.salt);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.create_time)) {
        this.create_time = data().deepCopy(fields()[12].schema(), other.create_time);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.last_update_time)) {
        this.last_update_time = data().deepCopy(fields()[13].schema(), other.last_update_time);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.status)) {
        this.status = data().deepCopy(fields()[14].schema(), other.status);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.score)) {
        this.score = data().deepCopy(fields()[15].schema(), other.score);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.app)) {
        this.app = data().deepCopy(fields()[16].schema(), other.app);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.level)) {
        this.level = data().deepCopy(fields()[17].schema(), other.level);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.level_upd_time)) {
        this.level_upd_time = data().deepCopy(fields()[18].schema(), other.level_upd_time);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.reward_flower_count)) {
        this.reward_flower_count = data().deepCopy(fields()[19].schema(), other.reward_flower_count);
        fieldSetFlags()[19] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ForumUserDelete instance
     * @param other The existing instance to copy.
     */
    private Builder(mypipe.avro.ForumUserDelete other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.nick_name)) {
        this.nick_name = data().deepCopy(fields()[6].schema(), other.nick_name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.user_sign)) {
        this.user_sign = data().deepCopy(fields()[7].schema(), other.user_sign);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.platform)) {
        this.platform = data().deepCopy(fields()[8].schema(), other.platform);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.passwd)) {
        this.passwd = data().deepCopy(fields()[9].schema(), other.passwd);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.head_url)) {
        this.head_url = data().deepCopy(fields()[10].schema(), other.head_url);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.salt)) {
        this.salt = data().deepCopy(fields()[11].schema(), other.salt);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.create_time)) {
        this.create_time = data().deepCopy(fields()[12].schema(), other.create_time);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.last_update_time)) {
        this.last_update_time = data().deepCopy(fields()[13].schema(), other.last_update_time);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.status)) {
        this.status = data().deepCopy(fields()[14].schema(), other.status);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.score)) {
        this.score = data().deepCopy(fields()[15].schema(), other.score);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.app)) {
        this.app = data().deepCopy(fields()[16].schema(), other.app);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.level)) {
        this.level = data().deepCopy(fields()[17].schema(), other.level);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.level_upd_time)) {
        this.level_upd_time = data().deepCopy(fields()[18].schema(), other.level_upd_time);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.reward_flower_count)) {
        this.reward_flower_count = data().deepCopy(fields()[19].schema(), other.reward_flower_count);
        fieldSetFlags()[19] = true;
      }
    }

    /**
      * Gets the value of the 'database' field.
      * @return The value.
      */
    public java.lang.CharSequence getDatabase() {
      return database;
    }

    /**
      * Sets the value of the 'database' field.
      * @param value The value of 'database'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setDatabase(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.database = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'database' field has been set.
      * @return True if the 'database' field has been set, false otherwise.
      */
    public boolean hasDatabase() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'database' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearDatabase() {
      database = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'table' field.
      * @return The value.
      */
    public java.lang.CharSequence getTable() {
      return table;
    }

    /**
      * Sets the value of the 'table' field.
      * @param value The value of 'table'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setTable(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.table = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'table' field has been set.
      * @return True if the 'table' field has been set, false otherwise.
      */
    public boolean hasTable() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'table' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearTable() {
      table = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tableId' field.
      * @return The value.
      */
    public java.lang.Integer getTableId() {
      return tableId;
    }

    /**
      * Sets the value of the 'tableId' field.
      * @param value The value of 'tableId'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setTableId(int value) {
      validate(fields()[2], value);
      this.tableId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tableId' field has been set.
      * @return True if the 'tableId' field has been set, false otherwise.
      */
    public boolean hasTableId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tableId' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearTableId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'txid' field.
      * @return The value.
      */
    public mypipe.avro.Guid getTxid() {
      return txid;
    }

    /**
      * Sets the value of the 'txid' field.
      * @param value The value of 'txid'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setTxid(mypipe.avro.Guid value) {
      validate(fields()[3], value);
      this.txid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'txid' field has been set.
      * @return True if the 'txid' field has been set, false otherwise.
      */
    public boolean hasTxid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'txid' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearTxid() {
      txid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setId(java.lang.Long value) {
      validate(fields()[5], value);
      this.id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearId() {
      id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'nick_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getNickName() {
      return nick_name;
    }

    /**
      * Sets the value of the 'nick_name' field.
      * @param value The value of 'nick_name'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setNickName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.nick_name = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'nick_name' field has been set.
      * @return True if the 'nick_name' field has been set, false otherwise.
      */
    public boolean hasNickName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'nick_name' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearNickName() {
      nick_name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_sign' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserSign() {
      return user_sign;
    }

    /**
      * Sets the value of the 'user_sign' field.
      * @param value The value of 'user_sign'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setUserSign(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.user_sign = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'user_sign' field has been set.
      * @return True if the 'user_sign' field has been set, false otherwise.
      */
    public boolean hasUserSign() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'user_sign' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearUserSign() {
      user_sign = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform' field.
      * @return The value.
      */
    public java.lang.Integer getPlatform() {
      return platform;
    }

    /**
      * Sets the value of the 'platform' field.
      * @param value The value of 'platform'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setPlatform(java.lang.Integer value) {
      validate(fields()[8], value);
      this.platform = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'platform' field has been set.
      * @return True if the 'platform' field has been set, false otherwise.
      */
    public boolean hasPlatform() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'platform' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'passwd' field.
      * @return The value.
      */
    public java.lang.CharSequence getPasswd() {
      return passwd;
    }

    /**
      * Sets the value of the 'passwd' field.
      * @param value The value of 'passwd'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setPasswd(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.passwd = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'passwd' field has been set.
      * @return True if the 'passwd' field has been set, false otherwise.
      */
    public boolean hasPasswd() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'passwd' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearPasswd() {
      passwd = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'head_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getHeadUrl() {
      return head_url;
    }

    /**
      * Sets the value of the 'head_url' field.
      * @param value The value of 'head_url'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setHeadUrl(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.head_url = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'head_url' field has been set.
      * @return True if the 'head_url' field has been set, false otherwise.
      */
    public boolean hasHeadUrl() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'head_url' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearHeadUrl() {
      head_url = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'salt' field.
      * @return The value.
      */
    public java.lang.CharSequence getSalt() {
      return salt;
    }

    /**
      * Sets the value of the 'salt' field.
      * @param value The value of 'salt'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setSalt(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.salt = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'salt' field has been set.
      * @return True if the 'salt' field has been set, false otherwise.
      */
    public boolean hasSalt() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'salt' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearSalt() {
      salt = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'create_time' field.
      * @return The value.
      */
    public java.lang.Long getCreateTime() {
      return create_time;
    }

    /**
      * Sets the value of the 'create_time' field.
      * @param value The value of 'create_time'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setCreateTime(java.lang.Long value) {
      validate(fields()[12], value);
      this.create_time = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'create_time' field has been set.
      * @return True if the 'create_time' field has been set, false otherwise.
      */
    public boolean hasCreateTime() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'create_time' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearCreateTime() {
      create_time = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_update_time' field.
      * @return The value.
      */
    public java.lang.Long getLastUpdateTime() {
      return last_update_time;
    }

    /**
      * Sets the value of the 'last_update_time' field.
      * @param value The value of 'last_update_time'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setLastUpdateTime(java.lang.Long value) {
      validate(fields()[13], value);
      this.last_update_time = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'last_update_time' field has been set.
      * @return True if the 'last_update_time' field has been set, false otherwise.
      */
    public boolean hasLastUpdateTime() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'last_update_time' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearLastUpdateTime() {
      last_update_time = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.Integer getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setStatus(java.lang.Integer value) {
      validate(fields()[14], value);
      this.status = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearStatus() {
      status = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'score' field.
      * @return The value.
      */
    public java.lang.Float getScore() {
      return score;
    }

    /**
      * Sets the value of the 'score' field.
      * @param value The value of 'score'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setScore(java.lang.Float value) {
      validate(fields()[15], value);
      this.score = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'score' field has been set.
      * @return True if the 'score' field has been set, false otherwise.
      */
    public boolean hasScore() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'score' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearScore() {
      score = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'app' field.
      * @return The value.
      */
    public java.lang.Integer getApp() {
      return app;
    }

    /**
      * Sets the value of the 'app' field.
      * @param value The value of 'app'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setApp(java.lang.Integer value) {
      validate(fields()[16], value);
      this.app = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'app' field has been set.
      * @return True if the 'app' field has been set, false otherwise.
      */
    public boolean hasApp() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'app' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearApp() {
      app = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'level' field.
      * @return The value.
      */
    public java.lang.Integer getLevel() {
      return level;
    }

    /**
      * Sets the value of the 'level' field.
      * @param value The value of 'level'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setLevel(java.lang.Integer value) {
      validate(fields()[17], value);
      this.level = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'level' field has been set.
      * @return True if the 'level' field has been set, false otherwise.
      */
    public boolean hasLevel() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'level' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearLevel() {
      level = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'level_upd_time' field.
      * @return The value.
      */
    public java.lang.Long getLevelUpdTime() {
      return level_upd_time;
    }

    /**
      * Sets the value of the 'level_upd_time' field.
      * @param value The value of 'level_upd_time'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setLevelUpdTime(java.lang.Long value) {
      validate(fields()[18], value);
      this.level_upd_time = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'level_upd_time' field has been set.
      * @return True if the 'level_upd_time' field has been set, false otherwise.
      */
    public boolean hasLevelUpdTime() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'level_upd_time' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearLevelUpdTime() {
      level_upd_time = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'reward_flower_count' field.
      * @return The value.
      */
    public java.lang.Integer getRewardFlowerCount() {
      return reward_flower_count;
    }

    /**
      * Sets the value of the 'reward_flower_count' field.
      * @param value The value of 'reward_flower_count'.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder setRewardFlowerCount(java.lang.Integer value) {
      validate(fields()[19], value);
      this.reward_flower_count = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'reward_flower_count' field has been set.
      * @return True if the 'reward_flower_count' field has been set, false otherwise.
      */
    public boolean hasRewardFlowerCount() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'reward_flower_count' field.
      * @return This builder.
      */
    public mypipe.avro.ForumUserDelete.Builder clearRewardFlowerCount() {
      reward_flower_count = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ForumUserDelete build() {
      try {
        ForumUserDelete record = new ForumUserDelete();
        record.database = fieldSetFlags()[0] ? this.database : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.table = fieldSetFlags()[1] ? this.table : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tableId = fieldSetFlags()[2] ? this.tableId : (java.lang.Integer) defaultValue(fields()[2]);
        record.txid = fieldSetFlags()[3] ? this.txid : (mypipe.avro.Guid) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.id = fieldSetFlags()[5] ? this.id : (java.lang.Long) defaultValue(fields()[5]);
        record.nick_name = fieldSetFlags()[6] ? this.nick_name : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.user_sign = fieldSetFlags()[7] ? this.user_sign : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.platform = fieldSetFlags()[8] ? this.platform : (java.lang.Integer) defaultValue(fields()[8]);
        record.passwd = fieldSetFlags()[9] ? this.passwd : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.head_url = fieldSetFlags()[10] ? this.head_url : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.salt = fieldSetFlags()[11] ? this.salt : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.create_time = fieldSetFlags()[12] ? this.create_time : (java.lang.Long) defaultValue(fields()[12]);
        record.last_update_time = fieldSetFlags()[13] ? this.last_update_time : (java.lang.Long) defaultValue(fields()[13]);
        record.status = fieldSetFlags()[14] ? this.status : (java.lang.Integer) defaultValue(fields()[14]);
        record.score = fieldSetFlags()[15] ? this.score : (java.lang.Float) defaultValue(fields()[15]);
        record.app = fieldSetFlags()[16] ? this.app : (java.lang.Integer) defaultValue(fields()[16]);
        record.level = fieldSetFlags()[17] ? this.level : (java.lang.Integer) defaultValue(fields()[17]);
        record.level_upd_time = fieldSetFlags()[18] ? this.level_upd_time : (java.lang.Long) defaultValue(fields()[18]);
        record.reward_flower_count = fieldSetFlags()[19] ? this.reward_flower_count : (java.lang.Integer) defaultValue(fields()[19]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ForumUserDelete>
    WRITER$ = (org.apache.avro.io.DatumWriter<ForumUserDelete>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ForumUserDelete>
    READER$ = (org.apache.avro.io.DatumReader<ForumUserDelete>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
