/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mypipe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ForumGroupInsert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6156679673057058705L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ForumGroupInsert\",\"namespace\":\"mypipe.avro\",\"fields\":[{\"name\":\"database\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"tableId\",\"type\":\"int\"},{\"name\":\"txid\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Guid\",\"size\":16}],\"default\":\"null\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"title\",\"type\":[\"string\",\"null\"]},{\"name\":\"description\",\"type\":[\"string\",\"null\"]},{\"name\":\"owner_ids\",\"type\":[\"string\",\"null\"]},{\"name\":\"last_update_time\",\"type\":[\"long\",\"null\"]},{\"name\":\"status\",\"type\":[\"int\",\"null\"]},{\"name\":\"pic_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"type\",\"type\":[\"int\",\"null\"]},{\"name\":\"key_words\",\"type\":[\"string\",\"null\"]},{\"name\":\"order_weight\",\"type\":[\"int\",\"null\"]},{\"name\":\"kind\",\"type\":[\"int\",\"null\"]},{\"name\":\"topic_order\",\"type\":[\"int\",\"null\"]},{\"name\":\"show_in_list\",\"type\":[\"int\",\"null\"]},{\"name\":\"detail_sort\",\"type\":[\"int\",\"null\"]},{\"name\":\"crawler_tag\",\"type\":[\"int\",\"null\"]},{\"name\":\"embody\",\"type\":[\"int\",\"null\"]},{\"name\":\"owner_id\",\"type\":[\"int\",\"null\"]},{\"name\":\"is_signin\",\"type\":[\"int\",\"null\"]},{\"name\":\"signin_start\",\"type\":[\"long\",\"null\"]},{\"name\":\"signin_end\",\"type\":[\"long\",\"null\"]},{\"name\":\"signin_times\",\"type\":[\"int\",\"null\"]},{\"name\":\"default_option\",\"type\":[\"string\",\"null\"]},{\"name\":\"read_only\",\"type\":[\"int\",\"null\"]},{\"name\":\"is_in_white_list\",\"type\":[\"int\",\"null\"]},{\"name\":\"anonymous\",\"type\":[\"int\",\"null\"]},{\"name\":\"sort_type\",\"type\":[\"int\",\"null\"]},{\"name\":\"embody_group\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ForumGroupInsert> ENCODER =
      new BinaryMessageEncoder<ForumGroupInsert>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ForumGroupInsert> DECODER =
      new BinaryMessageDecoder<ForumGroupInsert>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ForumGroupInsert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ForumGroupInsert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ForumGroupInsert>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ForumGroupInsert to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ForumGroupInsert from a ByteBuffer. */
  public static ForumGroupInsert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence database;
  @Deprecated public java.lang.CharSequence table;
  @Deprecated public int tableId;
  @Deprecated public mypipe.avro.Guid txid;
  @Deprecated public long timestamp;
  @Deprecated public java.lang.Integer id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public java.lang.CharSequence owner_ids;
  @Deprecated public java.lang.Long last_update_time;
  @Deprecated public java.lang.Integer status;
  @Deprecated public java.lang.CharSequence pic_url;
  @Deprecated public java.lang.Integer type;
  @Deprecated public java.lang.CharSequence key_words;
  @Deprecated public java.lang.Integer order_weight;
  @Deprecated public java.lang.Integer kind;
  @Deprecated public java.lang.Integer topic_order;
  @Deprecated public java.lang.Integer show_in_list;
  @Deprecated public java.lang.Integer detail_sort;
  @Deprecated public java.lang.Integer crawler_tag;
  @Deprecated public java.lang.Integer embody;
  @Deprecated public java.lang.Integer owner_id;
  @Deprecated public java.lang.Integer is_signin;
  @Deprecated public java.lang.Long signin_start;
  @Deprecated public java.lang.Long signin_end;
  @Deprecated public java.lang.Integer signin_times;
  @Deprecated public java.lang.CharSequence default_option;
  @Deprecated public java.lang.Integer read_only;
  @Deprecated public java.lang.Integer is_in_white_list;
  @Deprecated public java.lang.Integer anonymous;
  @Deprecated public java.lang.Integer sort_type;
  @Deprecated public java.lang.Integer embody_group;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ForumGroupInsert() {}

  /**
   * All-args constructor.
   * @param database The new value for database
   * @param table The new value for table
   * @param tableId The new value for tableId
   * @param txid The new value for txid
   * @param timestamp The new value for timestamp
   * @param id The new value for id
   * @param title The new value for title
   * @param description The new value for description
   * @param owner_ids The new value for owner_ids
   * @param last_update_time The new value for last_update_time
   * @param status The new value for status
   * @param pic_url The new value for pic_url
   * @param type The new value for type
   * @param key_words The new value for key_words
   * @param order_weight The new value for order_weight
   * @param kind The new value for kind
   * @param topic_order The new value for topic_order
   * @param show_in_list The new value for show_in_list
   * @param detail_sort The new value for detail_sort
   * @param crawler_tag The new value for crawler_tag
   * @param embody The new value for embody
   * @param owner_id The new value for owner_id
   * @param is_signin The new value for is_signin
   * @param signin_start The new value for signin_start
   * @param signin_end The new value for signin_end
   * @param signin_times The new value for signin_times
   * @param default_option The new value for default_option
   * @param read_only The new value for read_only
   * @param is_in_white_list The new value for is_in_white_list
   * @param anonymous The new value for anonymous
   * @param sort_type The new value for sort_type
   * @param embody_group The new value for embody_group
   */
  public ForumGroupInsert(java.lang.CharSequence database, java.lang.CharSequence table, java.lang.Integer tableId, mypipe.avro.Guid txid, java.lang.Long timestamp, java.lang.Integer id, java.lang.CharSequence title, java.lang.CharSequence description, java.lang.CharSequence owner_ids, java.lang.Long last_update_time, java.lang.Integer status, java.lang.CharSequence pic_url, java.lang.Integer type, java.lang.CharSequence key_words, java.lang.Integer order_weight, java.lang.Integer kind, java.lang.Integer topic_order, java.lang.Integer show_in_list, java.lang.Integer detail_sort, java.lang.Integer crawler_tag, java.lang.Integer embody, java.lang.Integer owner_id, java.lang.Integer is_signin, java.lang.Long signin_start, java.lang.Long signin_end, java.lang.Integer signin_times, java.lang.CharSequence default_option, java.lang.Integer read_only, java.lang.Integer is_in_white_list, java.lang.Integer anonymous, java.lang.Integer sort_type, java.lang.Integer embody_group) {
    this.database = database;
    this.table = table;
    this.tableId = tableId;
    this.txid = txid;
    this.timestamp = timestamp;
    this.id = id;
    this.title = title;
    this.description = description;
    this.owner_ids = owner_ids;
    this.last_update_time = last_update_time;
    this.status = status;
    this.pic_url = pic_url;
    this.type = type;
    this.key_words = key_words;
    this.order_weight = order_weight;
    this.kind = kind;
    this.topic_order = topic_order;
    this.show_in_list = show_in_list;
    this.detail_sort = detail_sort;
    this.crawler_tag = crawler_tag;
    this.embody = embody;
    this.owner_id = owner_id;
    this.is_signin = is_signin;
    this.signin_start = signin_start;
    this.signin_end = signin_end;
    this.signin_times = signin_times;
    this.default_option = default_option;
    this.read_only = read_only;
    this.is_in_white_list = is_in_white_list;
    this.anonymous = anonymous;
    this.sort_type = sort_type;
    this.embody_group = embody_group;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return database;
    case 1: return table;
    case 2: return tableId;
    case 3: return txid;
    case 4: return timestamp;
    case 5: return id;
    case 6: return title;
    case 7: return description;
    case 8: return owner_ids;
    case 9: return last_update_time;
    case 10: return status;
    case 11: return pic_url;
    case 12: return type;
    case 13: return key_words;
    case 14: return order_weight;
    case 15: return kind;
    case 16: return topic_order;
    case 17: return show_in_list;
    case 18: return detail_sort;
    case 19: return crawler_tag;
    case 20: return embody;
    case 21: return owner_id;
    case 22: return is_signin;
    case 23: return signin_start;
    case 24: return signin_end;
    case 25: return signin_times;
    case 26: return default_option;
    case 27: return read_only;
    case 28: return is_in_white_list;
    case 29: return anonymous;
    case 30: return sort_type;
    case 31: return embody_group;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: database = (java.lang.CharSequence)value$; break;
    case 1: table = (java.lang.CharSequence)value$; break;
    case 2: tableId = (java.lang.Integer)value$; break;
    case 3: txid = (mypipe.avro.Guid)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: id = (java.lang.Integer)value$; break;
    case 6: title = (java.lang.CharSequence)value$; break;
    case 7: description = (java.lang.CharSequence)value$; break;
    case 8: owner_ids = (java.lang.CharSequence)value$; break;
    case 9: last_update_time = (java.lang.Long)value$; break;
    case 10: status = (java.lang.Integer)value$; break;
    case 11: pic_url = (java.lang.CharSequence)value$; break;
    case 12: type = (java.lang.Integer)value$; break;
    case 13: key_words = (java.lang.CharSequence)value$; break;
    case 14: order_weight = (java.lang.Integer)value$; break;
    case 15: kind = (java.lang.Integer)value$; break;
    case 16: topic_order = (java.lang.Integer)value$; break;
    case 17: show_in_list = (java.lang.Integer)value$; break;
    case 18: detail_sort = (java.lang.Integer)value$; break;
    case 19: crawler_tag = (java.lang.Integer)value$; break;
    case 20: embody = (java.lang.Integer)value$; break;
    case 21: owner_id = (java.lang.Integer)value$; break;
    case 22: is_signin = (java.lang.Integer)value$; break;
    case 23: signin_start = (java.lang.Long)value$; break;
    case 24: signin_end = (java.lang.Long)value$; break;
    case 25: signin_times = (java.lang.Integer)value$; break;
    case 26: default_option = (java.lang.CharSequence)value$; break;
    case 27: read_only = (java.lang.Integer)value$; break;
    case 28: is_in_white_list = (java.lang.Integer)value$; break;
    case 29: anonymous = (java.lang.Integer)value$; break;
    case 30: sort_type = (java.lang.Integer)value$; break;
    case 31: embody_group = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'database' field.
   * @return The value of the 'database' field.
   */
  public java.lang.CharSequence getDatabase() {
    return database;
  }

  /**
   * Sets the value of the 'database' field.
   * @param value the value to set.
   */
  public void setDatabase(java.lang.CharSequence value) {
    this.database = value;
  }

  /**
   * Gets the value of the 'table' field.
   * @return The value of the 'table' field.
   */
  public java.lang.CharSequence getTable() {
    return table;
  }

  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(java.lang.CharSequence value) {
    this.table = value;
  }

  /**
   * Gets the value of the 'tableId' field.
   * @return The value of the 'tableId' field.
   */
  public java.lang.Integer getTableId() {
    return tableId;
  }

  /**
   * Sets the value of the 'tableId' field.
   * @param value the value to set.
   */
  public void setTableId(java.lang.Integer value) {
    this.tableId = value;
  }

  /**
   * Gets the value of the 'txid' field.
   * @return The value of the 'txid' field.
   */
  public mypipe.avro.Guid getTxid() {
    return txid;
  }

  /**
   * Sets the value of the 'txid' field.
   * @param value the value to set.
   */
  public void setTxid(mypipe.avro.Guid value) {
    this.txid = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'owner_ids' field.
   * @return The value of the 'owner_ids' field.
   */
  public java.lang.CharSequence getOwnerIds() {
    return owner_ids;
  }

  /**
   * Sets the value of the 'owner_ids' field.
   * @param value the value to set.
   */
  public void setOwnerIds(java.lang.CharSequence value) {
    this.owner_ids = value;
  }

  /**
   * Gets the value of the 'last_update_time' field.
   * @return The value of the 'last_update_time' field.
   */
  public java.lang.Long getLastUpdateTime() {
    return last_update_time;
  }

  /**
   * Sets the value of the 'last_update_time' field.
   * @param value the value to set.
   */
  public void setLastUpdateTime(java.lang.Long value) {
    this.last_update_time = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Integer value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'pic_url' field.
   * @return The value of the 'pic_url' field.
   */
  public java.lang.CharSequence getPicUrl() {
    return pic_url;
  }

  /**
   * Sets the value of the 'pic_url' field.
   * @param value the value to set.
   */
  public void setPicUrl(java.lang.CharSequence value) {
    this.pic_url = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.Integer getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.Integer value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'key_words' field.
   * @return The value of the 'key_words' field.
   */
  public java.lang.CharSequence getKeyWords() {
    return key_words;
  }

  /**
   * Sets the value of the 'key_words' field.
   * @param value the value to set.
   */
  public void setKeyWords(java.lang.CharSequence value) {
    this.key_words = value;
  }

  /**
   * Gets the value of the 'order_weight' field.
   * @return The value of the 'order_weight' field.
   */
  public java.lang.Integer getOrderWeight() {
    return order_weight;
  }

  /**
   * Sets the value of the 'order_weight' field.
   * @param value the value to set.
   */
  public void setOrderWeight(java.lang.Integer value) {
    this.order_weight = value;
  }

  /**
   * Gets the value of the 'kind' field.
   * @return The value of the 'kind' field.
   */
  public java.lang.Integer getKind() {
    return kind;
  }

  /**
   * Sets the value of the 'kind' field.
   * @param value the value to set.
   */
  public void setKind(java.lang.Integer value) {
    this.kind = value;
  }

  /**
   * Gets the value of the 'topic_order' field.
   * @return The value of the 'topic_order' field.
   */
  public java.lang.Integer getTopicOrder() {
    return topic_order;
  }

  /**
   * Sets the value of the 'topic_order' field.
   * @param value the value to set.
   */
  public void setTopicOrder(java.lang.Integer value) {
    this.topic_order = value;
  }

  /**
   * Gets the value of the 'show_in_list' field.
   * @return The value of the 'show_in_list' field.
   */
  public java.lang.Integer getShowInList() {
    return show_in_list;
  }

  /**
   * Sets the value of the 'show_in_list' field.
   * @param value the value to set.
   */
  public void setShowInList(java.lang.Integer value) {
    this.show_in_list = value;
  }

  /**
   * Gets the value of the 'detail_sort' field.
   * @return The value of the 'detail_sort' field.
   */
  public java.lang.Integer getDetailSort() {
    return detail_sort;
  }

  /**
   * Sets the value of the 'detail_sort' field.
   * @param value the value to set.
   */
  public void setDetailSort(java.lang.Integer value) {
    this.detail_sort = value;
  }

  /**
   * Gets the value of the 'crawler_tag' field.
   * @return The value of the 'crawler_tag' field.
   */
  public java.lang.Integer getCrawlerTag() {
    return crawler_tag;
  }

  /**
   * Sets the value of the 'crawler_tag' field.
   * @param value the value to set.
   */
  public void setCrawlerTag(java.lang.Integer value) {
    this.crawler_tag = value;
  }

  /**
   * Gets the value of the 'embody' field.
   * @return The value of the 'embody' field.
   */
  public java.lang.Integer getEmbody() {
    return embody;
  }

  /**
   * Sets the value of the 'embody' field.
   * @param value the value to set.
   */
  public void setEmbody(java.lang.Integer value) {
    this.embody = value;
  }

  /**
   * Gets the value of the 'owner_id' field.
   * @return The value of the 'owner_id' field.
   */
  public java.lang.Integer getOwnerId() {
    return owner_id;
  }

  /**
   * Sets the value of the 'owner_id' field.
   * @param value the value to set.
   */
  public void setOwnerId(java.lang.Integer value) {
    this.owner_id = value;
  }

  /**
   * Gets the value of the 'is_signin' field.
   * @return The value of the 'is_signin' field.
   */
  public java.lang.Integer getIsSignin() {
    return is_signin;
  }

  /**
   * Sets the value of the 'is_signin' field.
   * @param value the value to set.
   */
  public void setIsSignin(java.lang.Integer value) {
    this.is_signin = value;
  }

  /**
   * Gets the value of the 'signin_start' field.
   * @return The value of the 'signin_start' field.
   */
  public java.lang.Long getSigninStart() {
    return signin_start;
  }

  /**
   * Sets the value of the 'signin_start' field.
   * @param value the value to set.
   */
  public void setSigninStart(java.lang.Long value) {
    this.signin_start = value;
  }

  /**
   * Gets the value of the 'signin_end' field.
   * @return The value of the 'signin_end' field.
   */
  public java.lang.Long getSigninEnd() {
    return signin_end;
  }

  /**
   * Sets the value of the 'signin_end' field.
   * @param value the value to set.
   */
  public void setSigninEnd(java.lang.Long value) {
    this.signin_end = value;
  }

  /**
   * Gets the value of the 'signin_times' field.
   * @return The value of the 'signin_times' field.
   */
  public java.lang.Integer getSigninTimes() {
    return signin_times;
  }

  /**
   * Sets the value of the 'signin_times' field.
   * @param value the value to set.
   */
  public void setSigninTimes(java.lang.Integer value) {
    this.signin_times = value;
  }

  /**
   * Gets the value of the 'default_option' field.
   * @return The value of the 'default_option' field.
   */
  public java.lang.CharSequence getDefaultOption() {
    return default_option;
  }

  /**
   * Sets the value of the 'default_option' field.
   * @param value the value to set.
   */
  public void setDefaultOption(java.lang.CharSequence value) {
    this.default_option = value;
  }

  /**
   * Gets the value of the 'read_only' field.
   * @return The value of the 'read_only' field.
   */
  public java.lang.Integer getReadOnly() {
    return read_only;
  }

  /**
   * Sets the value of the 'read_only' field.
   * @param value the value to set.
   */
  public void setReadOnly(java.lang.Integer value) {
    this.read_only = value;
  }

  /**
   * Gets the value of the 'is_in_white_list' field.
   * @return The value of the 'is_in_white_list' field.
   */
  public java.lang.Integer getIsInWhiteList() {
    return is_in_white_list;
  }

  /**
   * Sets the value of the 'is_in_white_list' field.
   * @param value the value to set.
   */
  public void setIsInWhiteList(java.lang.Integer value) {
    this.is_in_white_list = value;
  }

  /**
   * Gets the value of the 'anonymous' field.
   * @return The value of the 'anonymous' field.
   */
  public java.lang.Integer getAnonymous() {
    return anonymous;
  }

  /**
   * Sets the value of the 'anonymous' field.
   * @param value the value to set.
   */
  public void setAnonymous(java.lang.Integer value) {
    this.anonymous = value;
  }

  /**
   * Gets the value of the 'sort_type' field.
   * @return The value of the 'sort_type' field.
   */
  public java.lang.Integer getSortType() {
    return sort_type;
  }

  /**
   * Sets the value of the 'sort_type' field.
   * @param value the value to set.
   */
  public void setSortType(java.lang.Integer value) {
    this.sort_type = value;
  }

  /**
   * Gets the value of the 'embody_group' field.
   * @return The value of the 'embody_group' field.
   */
  public java.lang.Integer getEmbodyGroup() {
    return embody_group;
  }

  /**
   * Sets the value of the 'embody_group' field.
   * @param value the value to set.
   */
  public void setEmbodyGroup(java.lang.Integer value) {
    this.embody_group = value;
  }

  /**
   * Creates a new ForumGroupInsert RecordBuilder.
   * @return A new ForumGroupInsert RecordBuilder
   */
  public static mypipe.avro.ForumGroupInsert.Builder newBuilder() {
    return new mypipe.avro.ForumGroupInsert.Builder();
  }

  /**
   * Creates a new ForumGroupInsert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ForumGroupInsert RecordBuilder
   */
  public static mypipe.avro.ForumGroupInsert.Builder newBuilder(mypipe.avro.ForumGroupInsert.Builder other) {
    return new mypipe.avro.ForumGroupInsert.Builder(other);
  }

  /**
   * Creates a new ForumGroupInsert RecordBuilder by copying an existing ForumGroupInsert instance.
   * @param other The existing instance to copy.
   * @return A new ForumGroupInsert RecordBuilder
   */
  public static mypipe.avro.ForumGroupInsert.Builder newBuilder(mypipe.avro.ForumGroupInsert other) {
    return new mypipe.avro.ForumGroupInsert.Builder(other);
  }

  /**
   * RecordBuilder for ForumGroupInsert instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ForumGroupInsert>
    implements org.apache.avro.data.RecordBuilder<ForumGroupInsert> {

    private java.lang.CharSequence database;
    private java.lang.CharSequence table;
    private int tableId;
    private mypipe.avro.Guid txid;
    private long timestamp;
    private java.lang.Integer id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence description;
    private java.lang.CharSequence owner_ids;
    private java.lang.Long last_update_time;
    private java.lang.Integer status;
    private java.lang.CharSequence pic_url;
    private java.lang.Integer type;
    private java.lang.CharSequence key_words;
    private java.lang.Integer order_weight;
    private java.lang.Integer kind;
    private java.lang.Integer topic_order;
    private java.lang.Integer show_in_list;
    private java.lang.Integer detail_sort;
    private java.lang.Integer crawler_tag;
    private java.lang.Integer embody;
    private java.lang.Integer owner_id;
    private java.lang.Integer is_signin;
    private java.lang.Long signin_start;
    private java.lang.Long signin_end;
    private java.lang.Integer signin_times;
    private java.lang.CharSequence default_option;
    private java.lang.Integer read_only;
    private java.lang.Integer is_in_white_list;
    private java.lang.Integer anonymous;
    private java.lang.Integer sort_type;
    private java.lang.Integer embody_group;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mypipe.avro.ForumGroupInsert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.description)) {
        this.description = data().deepCopy(fields()[7].schema(), other.description);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.owner_ids)) {
        this.owner_ids = data().deepCopy(fields()[8].schema(), other.owner_ids);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.last_update_time)) {
        this.last_update_time = data().deepCopy(fields()[9].schema(), other.last_update_time);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.status)) {
        this.status = data().deepCopy(fields()[10].schema(), other.status);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.pic_url)) {
        this.pic_url = data().deepCopy(fields()[11].schema(), other.pic_url);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.type)) {
        this.type = data().deepCopy(fields()[12].schema(), other.type);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.key_words)) {
        this.key_words = data().deepCopy(fields()[13].schema(), other.key_words);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.order_weight)) {
        this.order_weight = data().deepCopy(fields()[14].schema(), other.order_weight);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.kind)) {
        this.kind = data().deepCopy(fields()[15].schema(), other.kind);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.topic_order)) {
        this.topic_order = data().deepCopy(fields()[16].schema(), other.topic_order);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.show_in_list)) {
        this.show_in_list = data().deepCopy(fields()[17].schema(), other.show_in_list);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.detail_sort)) {
        this.detail_sort = data().deepCopy(fields()[18].schema(), other.detail_sort);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.crawler_tag)) {
        this.crawler_tag = data().deepCopy(fields()[19].schema(), other.crawler_tag);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.embody)) {
        this.embody = data().deepCopy(fields()[20].schema(), other.embody);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.owner_id)) {
        this.owner_id = data().deepCopy(fields()[21].schema(), other.owner_id);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.is_signin)) {
        this.is_signin = data().deepCopy(fields()[22].schema(), other.is_signin);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.signin_start)) {
        this.signin_start = data().deepCopy(fields()[23].schema(), other.signin_start);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.signin_end)) {
        this.signin_end = data().deepCopy(fields()[24].schema(), other.signin_end);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.signin_times)) {
        this.signin_times = data().deepCopy(fields()[25].schema(), other.signin_times);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.default_option)) {
        this.default_option = data().deepCopy(fields()[26].schema(), other.default_option);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.read_only)) {
        this.read_only = data().deepCopy(fields()[27].schema(), other.read_only);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.is_in_white_list)) {
        this.is_in_white_list = data().deepCopy(fields()[28].schema(), other.is_in_white_list);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.anonymous)) {
        this.anonymous = data().deepCopy(fields()[29].schema(), other.anonymous);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.sort_type)) {
        this.sort_type = data().deepCopy(fields()[30].schema(), other.sort_type);
        fieldSetFlags()[30] = true;
      }
      if (isValidValue(fields()[31], other.embody_group)) {
        this.embody_group = data().deepCopy(fields()[31].schema(), other.embody_group);
        fieldSetFlags()[31] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ForumGroupInsert instance
     * @param other The existing instance to copy.
     */
    private Builder(mypipe.avro.ForumGroupInsert other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.database)) {
        this.database = data().deepCopy(fields()[0].schema(), other.database);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.table)) {
        this.table = data().deepCopy(fields()[1].schema(), other.table);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tableId)) {
        this.tableId = data().deepCopy(fields()[2].schema(), other.tableId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.txid)) {
        this.txid = data().deepCopy(fields()[3].schema(), other.txid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id)) {
        this.id = data().deepCopy(fields()[5].schema(), other.id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.description)) {
        this.description = data().deepCopy(fields()[7].schema(), other.description);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.owner_ids)) {
        this.owner_ids = data().deepCopy(fields()[8].schema(), other.owner_ids);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.last_update_time)) {
        this.last_update_time = data().deepCopy(fields()[9].schema(), other.last_update_time);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.status)) {
        this.status = data().deepCopy(fields()[10].schema(), other.status);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.pic_url)) {
        this.pic_url = data().deepCopy(fields()[11].schema(), other.pic_url);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.type)) {
        this.type = data().deepCopy(fields()[12].schema(), other.type);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.key_words)) {
        this.key_words = data().deepCopy(fields()[13].schema(), other.key_words);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.order_weight)) {
        this.order_weight = data().deepCopy(fields()[14].schema(), other.order_weight);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.kind)) {
        this.kind = data().deepCopy(fields()[15].schema(), other.kind);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.topic_order)) {
        this.topic_order = data().deepCopy(fields()[16].schema(), other.topic_order);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.show_in_list)) {
        this.show_in_list = data().deepCopy(fields()[17].schema(), other.show_in_list);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.detail_sort)) {
        this.detail_sort = data().deepCopy(fields()[18].schema(), other.detail_sort);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.crawler_tag)) {
        this.crawler_tag = data().deepCopy(fields()[19].schema(), other.crawler_tag);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.embody)) {
        this.embody = data().deepCopy(fields()[20].schema(), other.embody);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.owner_id)) {
        this.owner_id = data().deepCopy(fields()[21].schema(), other.owner_id);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.is_signin)) {
        this.is_signin = data().deepCopy(fields()[22].schema(), other.is_signin);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.signin_start)) {
        this.signin_start = data().deepCopy(fields()[23].schema(), other.signin_start);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.signin_end)) {
        this.signin_end = data().deepCopy(fields()[24].schema(), other.signin_end);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.signin_times)) {
        this.signin_times = data().deepCopy(fields()[25].schema(), other.signin_times);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.default_option)) {
        this.default_option = data().deepCopy(fields()[26].schema(), other.default_option);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.read_only)) {
        this.read_only = data().deepCopy(fields()[27].schema(), other.read_only);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.is_in_white_list)) {
        this.is_in_white_list = data().deepCopy(fields()[28].schema(), other.is_in_white_list);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.anonymous)) {
        this.anonymous = data().deepCopy(fields()[29].schema(), other.anonymous);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.sort_type)) {
        this.sort_type = data().deepCopy(fields()[30].schema(), other.sort_type);
        fieldSetFlags()[30] = true;
      }
      if (isValidValue(fields()[31], other.embody_group)) {
        this.embody_group = data().deepCopy(fields()[31].schema(), other.embody_group);
        fieldSetFlags()[31] = true;
      }
    }

    /**
      * Gets the value of the 'database' field.
      * @return The value.
      */
    public java.lang.CharSequence getDatabase() {
      return database;
    }

    /**
      * Sets the value of the 'database' field.
      * @param value The value of 'database'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setDatabase(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.database = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'database' field has been set.
      * @return True if the 'database' field has been set, false otherwise.
      */
    public boolean hasDatabase() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'database' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearDatabase() {
      database = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'table' field.
      * @return The value.
      */
    public java.lang.CharSequence getTable() {
      return table;
    }

    /**
      * Sets the value of the 'table' field.
      * @param value The value of 'table'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setTable(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.table = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'table' field has been set.
      * @return True if the 'table' field has been set, false otherwise.
      */
    public boolean hasTable() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'table' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearTable() {
      table = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tableId' field.
      * @return The value.
      */
    public java.lang.Integer getTableId() {
      return tableId;
    }

    /**
      * Sets the value of the 'tableId' field.
      * @param value The value of 'tableId'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setTableId(int value) {
      validate(fields()[2], value);
      this.tableId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tableId' field has been set.
      * @return True if the 'tableId' field has been set, false otherwise.
      */
    public boolean hasTableId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tableId' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearTableId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'txid' field.
      * @return The value.
      */
    public mypipe.avro.Guid getTxid() {
      return txid;
    }

    /**
      * Sets the value of the 'txid' field.
      * @param value The value of 'txid'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setTxid(mypipe.avro.Guid value) {
      validate(fields()[3], value);
      this.txid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'txid' field has been set.
      * @return True if the 'txid' field has been set, false otherwise.
      */
    public boolean hasTxid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'txid' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearTxid() {
      txid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setId(java.lang.Integer value) {
      validate(fields()[5], value);
      this.id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearId() {
      id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }

    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.title = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearTitle() {
      title = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.description = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearDescription() {
      description = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner_ids' field.
      * @return The value.
      */
    public java.lang.CharSequence getOwnerIds() {
      return owner_ids;
    }

    /**
      * Sets the value of the 'owner_ids' field.
      * @param value The value of 'owner_ids'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setOwnerIds(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.owner_ids = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'owner_ids' field has been set.
      * @return True if the 'owner_ids' field has been set, false otherwise.
      */
    public boolean hasOwnerIds() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'owner_ids' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearOwnerIds() {
      owner_ids = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_update_time' field.
      * @return The value.
      */
    public java.lang.Long getLastUpdateTime() {
      return last_update_time;
    }

    /**
      * Sets the value of the 'last_update_time' field.
      * @param value The value of 'last_update_time'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setLastUpdateTime(java.lang.Long value) {
      validate(fields()[9], value);
      this.last_update_time = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'last_update_time' field has been set.
      * @return True if the 'last_update_time' field has been set, false otherwise.
      */
    public boolean hasLastUpdateTime() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'last_update_time' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearLastUpdateTime() {
      last_update_time = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.Integer getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setStatus(java.lang.Integer value) {
      validate(fields()[10], value);
      this.status = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearStatus() {
      status = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'pic_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getPicUrl() {
      return pic_url;
    }

    /**
      * Sets the value of the 'pic_url' field.
      * @param value The value of 'pic_url'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setPicUrl(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.pic_url = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'pic_url' field has been set.
      * @return True if the 'pic_url' field has been set, false otherwise.
      */
    public boolean hasPicUrl() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'pic_url' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearPicUrl() {
      pic_url = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.Integer getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setType(java.lang.Integer value) {
      validate(fields()[12], value);
      this.type = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearType() {
      type = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'key_words' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeyWords() {
      return key_words;
    }

    /**
      * Sets the value of the 'key_words' field.
      * @param value The value of 'key_words'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setKeyWords(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.key_words = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'key_words' field has been set.
      * @return True if the 'key_words' field has been set, false otherwise.
      */
    public boolean hasKeyWords() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'key_words' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearKeyWords() {
      key_words = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'order_weight' field.
      * @return The value.
      */
    public java.lang.Integer getOrderWeight() {
      return order_weight;
    }

    /**
      * Sets the value of the 'order_weight' field.
      * @param value The value of 'order_weight'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setOrderWeight(java.lang.Integer value) {
      validate(fields()[14], value);
      this.order_weight = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'order_weight' field has been set.
      * @return True if the 'order_weight' field has been set, false otherwise.
      */
    public boolean hasOrderWeight() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'order_weight' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearOrderWeight() {
      order_weight = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'kind' field.
      * @return The value.
      */
    public java.lang.Integer getKind() {
      return kind;
    }

    /**
      * Sets the value of the 'kind' field.
      * @param value The value of 'kind'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setKind(java.lang.Integer value) {
      validate(fields()[15], value);
      this.kind = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'kind' field has been set.
      * @return True if the 'kind' field has been set, false otherwise.
      */
    public boolean hasKind() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'kind' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearKind() {
      kind = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'topic_order' field.
      * @return The value.
      */
    public java.lang.Integer getTopicOrder() {
      return topic_order;
    }

    /**
      * Sets the value of the 'topic_order' field.
      * @param value The value of 'topic_order'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setTopicOrder(java.lang.Integer value) {
      validate(fields()[16], value);
      this.topic_order = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'topic_order' field has been set.
      * @return True if the 'topic_order' field has been set, false otherwise.
      */
    public boolean hasTopicOrder() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'topic_order' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearTopicOrder() {
      topic_order = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'show_in_list' field.
      * @return The value.
      */
    public java.lang.Integer getShowInList() {
      return show_in_list;
    }

    /**
      * Sets the value of the 'show_in_list' field.
      * @param value The value of 'show_in_list'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setShowInList(java.lang.Integer value) {
      validate(fields()[17], value);
      this.show_in_list = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'show_in_list' field has been set.
      * @return True if the 'show_in_list' field has been set, false otherwise.
      */
    public boolean hasShowInList() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'show_in_list' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearShowInList() {
      show_in_list = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'detail_sort' field.
      * @return The value.
      */
    public java.lang.Integer getDetailSort() {
      return detail_sort;
    }

    /**
      * Sets the value of the 'detail_sort' field.
      * @param value The value of 'detail_sort'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setDetailSort(java.lang.Integer value) {
      validate(fields()[18], value);
      this.detail_sort = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'detail_sort' field has been set.
      * @return True if the 'detail_sort' field has been set, false otherwise.
      */
    public boolean hasDetailSort() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'detail_sort' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearDetailSort() {
      detail_sort = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'crawler_tag' field.
      * @return The value.
      */
    public java.lang.Integer getCrawlerTag() {
      return crawler_tag;
    }

    /**
      * Sets the value of the 'crawler_tag' field.
      * @param value The value of 'crawler_tag'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setCrawlerTag(java.lang.Integer value) {
      validate(fields()[19], value);
      this.crawler_tag = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'crawler_tag' field has been set.
      * @return True if the 'crawler_tag' field has been set, false otherwise.
      */
    public boolean hasCrawlerTag() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'crawler_tag' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearCrawlerTag() {
      crawler_tag = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'embody' field.
      * @return The value.
      */
    public java.lang.Integer getEmbody() {
      return embody;
    }

    /**
      * Sets the value of the 'embody' field.
      * @param value The value of 'embody'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setEmbody(java.lang.Integer value) {
      validate(fields()[20], value);
      this.embody = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'embody' field has been set.
      * @return True if the 'embody' field has been set, false otherwise.
      */
    public boolean hasEmbody() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'embody' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearEmbody() {
      embody = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner_id' field.
      * @return The value.
      */
    public java.lang.Integer getOwnerId() {
      return owner_id;
    }

    /**
      * Sets the value of the 'owner_id' field.
      * @param value The value of 'owner_id'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setOwnerId(java.lang.Integer value) {
      validate(fields()[21], value);
      this.owner_id = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'owner_id' field has been set.
      * @return True if the 'owner_id' field has been set, false otherwise.
      */
    public boolean hasOwnerId() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'owner_id' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearOwnerId() {
      owner_id = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'is_signin' field.
      * @return The value.
      */
    public java.lang.Integer getIsSignin() {
      return is_signin;
    }

    /**
      * Sets the value of the 'is_signin' field.
      * @param value The value of 'is_signin'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setIsSignin(java.lang.Integer value) {
      validate(fields()[22], value);
      this.is_signin = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'is_signin' field has been set.
      * @return True if the 'is_signin' field has been set, false otherwise.
      */
    public boolean hasIsSignin() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'is_signin' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearIsSignin() {
      is_signin = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'signin_start' field.
      * @return The value.
      */
    public java.lang.Long getSigninStart() {
      return signin_start;
    }

    /**
      * Sets the value of the 'signin_start' field.
      * @param value The value of 'signin_start'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setSigninStart(java.lang.Long value) {
      validate(fields()[23], value);
      this.signin_start = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'signin_start' field has been set.
      * @return True if the 'signin_start' field has been set, false otherwise.
      */
    public boolean hasSigninStart() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'signin_start' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearSigninStart() {
      signin_start = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'signin_end' field.
      * @return The value.
      */
    public java.lang.Long getSigninEnd() {
      return signin_end;
    }

    /**
      * Sets the value of the 'signin_end' field.
      * @param value The value of 'signin_end'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setSigninEnd(java.lang.Long value) {
      validate(fields()[24], value);
      this.signin_end = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'signin_end' field has been set.
      * @return True if the 'signin_end' field has been set, false otherwise.
      */
    public boolean hasSigninEnd() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'signin_end' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearSigninEnd() {
      signin_end = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'signin_times' field.
      * @return The value.
      */
    public java.lang.Integer getSigninTimes() {
      return signin_times;
    }

    /**
      * Sets the value of the 'signin_times' field.
      * @param value The value of 'signin_times'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setSigninTimes(java.lang.Integer value) {
      validate(fields()[25], value);
      this.signin_times = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'signin_times' field has been set.
      * @return True if the 'signin_times' field has been set, false otherwise.
      */
    public boolean hasSigninTimes() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'signin_times' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearSigninTimes() {
      signin_times = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'default_option' field.
      * @return The value.
      */
    public java.lang.CharSequence getDefaultOption() {
      return default_option;
    }

    /**
      * Sets the value of the 'default_option' field.
      * @param value The value of 'default_option'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setDefaultOption(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.default_option = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'default_option' field has been set.
      * @return True if the 'default_option' field has been set, false otherwise.
      */
    public boolean hasDefaultOption() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'default_option' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearDefaultOption() {
      default_option = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'read_only' field.
      * @return The value.
      */
    public java.lang.Integer getReadOnly() {
      return read_only;
    }

    /**
      * Sets the value of the 'read_only' field.
      * @param value The value of 'read_only'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setReadOnly(java.lang.Integer value) {
      validate(fields()[27], value);
      this.read_only = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'read_only' field has been set.
      * @return True if the 'read_only' field has been set, false otherwise.
      */
    public boolean hasReadOnly() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'read_only' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearReadOnly() {
      read_only = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    /**
      * Gets the value of the 'is_in_white_list' field.
      * @return The value.
      */
    public java.lang.Integer getIsInWhiteList() {
      return is_in_white_list;
    }

    /**
      * Sets the value of the 'is_in_white_list' field.
      * @param value The value of 'is_in_white_list'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setIsInWhiteList(java.lang.Integer value) {
      validate(fields()[28], value);
      this.is_in_white_list = value;
      fieldSetFlags()[28] = true;
      return this;
    }

    /**
      * Checks whether the 'is_in_white_list' field has been set.
      * @return True if the 'is_in_white_list' field has been set, false otherwise.
      */
    public boolean hasIsInWhiteList() {
      return fieldSetFlags()[28];
    }


    /**
      * Clears the value of the 'is_in_white_list' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearIsInWhiteList() {
      is_in_white_list = null;
      fieldSetFlags()[28] = false;
      return this;
    }

    /**
      * Gets the value of the 'anonymous' field.
      * @return The value.
      */
    public java.lang.Integer getAnonymous() {
      return anonymous;
    }

    /**
      * Sets the value of the 'anonymous' field.
      * @param value The value of 'anonymous'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setAnonymous(java.lang.Integer value) {
      validate(fields()[29], value);
      this.anonymous = value;
      fieldSetFlags()[29] = true;
      return this;
    }

    /**
      * Checks whether the 'anonymous' field has been set.
      * @return True if the 'anonymous' field has been set, false otherwise.
      */
    public boolean hasAnonymous() {
      return fieldSetFlags()[29];
    }


    /**
      * Clears the value of the 'anonymous' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearAnonymous() {
      anonymous = null;
      fieldSetFlags()[29] = false;
      return this;
    }

    /**
      * Gets the value of the 'sort_type' field.
      * @return The value.
      */
    public java.lang.Integer getSortType() {
      return sort_type;
    }

    /**
      * Sets the value of the 'sort_type' field.
      * @param value The value of 'sort_type'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setSortType(java.lang.Integer value) {
      validate(fields()[30], value);
      this.sort_type = value;
      fieldSetFlags()[30] = true;
      return this;
    }

    /**
      * Checks whether the 'sort_type' field has been set.
      * @return True if the 'sort_type' field has been set, false otherwise.
      */
    public boolean hasSortType() {
      return fieldSetFlags()[30];
    }


    /**
      * Clears the value of the 'sort_type' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearSortType() {
      sort_type = null;
      fieldSetFlags()[30] = false;
      return this;
    }

    /**
      * Gets the value of the 'embody_group' field.
      * @return The value.
      */
    public java.lang.Integer getEmbodyGroup() {
      return embody_group;
    }

    /**
      * Sets the value of the 'embody_group' field.
      * @param value The value of 'embody_group'.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder setEmbodyGroup(java.lang.Integer value) {
      validate(fields()[31], value);
      this.embody_group = value;
      fieldSetFlags()[31] = true;
      return this;
    }

    /**
      * Checks whether the 'embody_group' field has been set.
      * @return True if the 'embody_group' field has been set, false otherwise.
      */
    public boolean hasEmbodyGroup() {
      return fieldSetFlags()[31];
    }


    /**
      * Clears the value of the 'embody_group' field.
      * @return This builder.
      */
    public mypipe.avro.ForumGroupInsert.Builder clearEmbodyGroup() {
      embody_group = null;
      fieldSetFlags()[31] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ForumGroupInsert build() {
      try {
        ForumGroupInsert record = new ForumGroupInsert();
        record.database = fieldSetFlags()[0] ? this.database : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.table = fieldSetFlags()[1] ? this.table : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tableId = fieldSetFlags()[2] ? this.tableId : (java.lang.Integer) defaultValue(fields()[2]);
        record.txid = fieldSetFlags()[3] ? this.txid : (mypipe.avro.Guid) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.id = fieldSetFlags()[5] ? this.id : (java.lang.Integer) defaultValue(fields()[5]);
        record.title = fieldSetFlags()[6] ? this.title : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.description = fieldSetFlags()[7] ? this.description : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.owner_ids = fieldSetFlags()[8] ? this.owner_ids : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.last_update_time = fieldSetFlags()[9] ? this.last_update_time : (java.lang.Long) defaultValue(fields()[9]);
        record.status = fieldSetFlags()[10] ? this.status : (java.lang.Integer) defaultValue(fields()[10]);
        record.pic_url = fieldSetFlags()[11] ? this.pic_url : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.type = fieldSetFlags()[12] ? this.type : (java.lang.Integer) defaultValue(fields()[12]);
        record.key_words = fieldSetFlags()[13] ? this.key_words : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.order_weight = fieldSetFlags()[14] ? this.order_weight : (java.lang.Integer) defaultValue(fields()[14]);
        record.kind = fieldSetFlags()[15] ? this.kind : (java.lang.Integer) defaultValue(fields()[15]);
        record.topic_order = fieldSetFlags()[16] ? this.topic_order : (java.lang.Integer) defaultValue(fields()[16]);
        record.show_in_list = fieldSetFlags()[17] ? this.show_in_list : (java.lang.Integer) defaultValue(fields()[17]);
        record.detail_sort = fieldSetFlags()[18] ? this.detail_sort : (java.lang.Integer) defaultValue(fields()[18]);
        record.crawler_tag = fieldSetFlags()[19] ? this.crawler_tag : (java.lang.Integer) defaultValue(fields()[19]);
        record.embody = fieldSetFlags()[20] ? this.embody : (java.lang.Integer) defaultValue(fields()[20]);
        record.owner_id = fieldSetFlags()[21] ? this.owner_id : (java.lang.Integer) defaultValue(fields()[21]);
        record.is_signin = fieldSetFlags()[22] ? this.is_signin : (java.lang.Integer) defaultValue(fields()[22]);
        record.signin_start = fieldSetFlags()[23] ? this.signin_start : (java.lang.Long) defaultValue(fields()[23]);
        record.signin_end = fieldSetFlags()[24] ? this.signin_end : (java.lang.Long) defaultValue(fields()[24]);
        record.signin_times = fieldSetFlags()[25] ? this.signin_times : (java.lang.Integer) defaultValue(fields()[25]);
        record.default_option = fieldSetFlags()[26] ? this.default_option : (java.lang.CharSequence) defaultValue(fields()[26]);
        record.read_only = fieldSetFlags()[27] ? this.read_only : (java.lang.Integer) defaultValue(fields()[27]);
        record.is_in_white_list = fieldSetFlags()[28] ? this.is_in_white_list : (java.lang.Integer) defaultValue(fields()[28]);
        record.anonymous = fieldSetFlags()[29] ? this.anonymous : (java.lang.Integer) defaultValue(fields()[29]);
        record.sort_type = fieldSetFlags()[30] ? this.sort_type : (java.lang.Integer) defaultValue(fields()[30]);
        record.embody_group = fieldSetFlags()[31] ? this.embody_group : (java.lang.Integer) defaultValue(fields()[31]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ForumGroupInsert>
    WRITER$ = (org.apache.avro.io.DatumWriter<ForumGroupInsert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ForumGroupInsert>
    READER$ = (org.apache.avro.io.DatumReader<ForumGroupInsert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
